"""Tests for the v2.0.11 owner decision pack (read-only, deterministic, no LLM).

The pack is generated by ``scripts/corpus_v2_v211_targeted_remaining22_decision_pack.py``
and covers the 22 targeted-review items (18 substantive rejects + 4 persistent
contract errors).  It never rewrites the v2.0.11 candidate or the targeted
review; it never calls a model; all mechanical classifications are recomputed
from the current v2.0.11 evidence raw spans and the same-source chunk texts.
"""

import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts import corpus_v2_v211_targeted_remaining22_decision_pack as dp  # noqa: E402

REV = ROOT / "evaluation/datasets/v2/revisions"
V211 = REV / "v2.0.11-owner-authorized-en048-same-source-repair"
V210 = REV / "v2.0.10-owner-authorized-coherence-remediation"
V208 = REV / "v2.0.8-owner-authorized-semantic-quality-remediation"
CHUNKS_PATH = ROOT / "data/v2-corpus/chunks/chunks.jsonl"
CHUNK_MANIFEST_PATH = ROOT / "data/v2-corpus/chunks/chunk-manifest.json"
CURRENT_DRAFT_PATH = ROOT / "evaluation/datasets/v2/annotations/v2-cases-draft.jsonl"

EXPECTED_REJECT_IDS = [
    "en-040", "en-041", "en-045", "en-047", "en-051",
    "mixed-022", "mixed-028", "mixed-029", "mixed-034",
    "multi-012", "multi-027",
    "zh-023", "zh-036", "zh-046", "zh-050", "zh-052", "zh-054", "zh-058",
]
EXPECTED_ERROR_IDS = ["en-052", "mixed-030", "mixed-033", "zh-040"]
EXPECTED_TARGET_IDS = sorted(EXPECTED_REJECT_IDS + EXPECTED_ERROR_IDS)

# Case-level mechanical classification (weakest answer point wins):
#   exact 7 / partial 7 / translation 4 / same_source 0 / no_direct 0
CASE_CLASSIFICATION_EXPECTED = {
    "en-040": "translation", "en-041": "partial", "en-045": "partial",
    "en-047": "translation", "en-051": "partial",
    "mixed-022": "exact", "mixed-028": "exact", "mixed-029": "exact",
    "mixed-034": "partial",
    "multi-012": "exact", "multi-027": "partial",
    "zh-023": "exact", "zh-036": "exact", "zh-046": "translation",
    "zh-050": "partial", "zh-052": "translation", "zh-054": "exact",
    "zh-058": "partial",
}
AP_CLASSIFICATION_COUNTS_EXPECTED = {
    "exact": 7, "partial": 12, "translation": 8,
    "same_source": 0, "no_direct": 0,
}


# ── fixtures / helpers ──────────────────────────────────────────────────

@pytest.fixture()
def inputs(tmp_path):
    """Copy the real v2.0.11 / v2.0.10 trees and corpus files into tmp_path."""
    shutil.copytree(V211, tmp_path / "v211")
    shutil.copytree(V210, tmp_path / "v210")
    for src, name in ((CHUNKS_PATH, "chunks.jsonl"),
                      (CHUNK_MANIFEST_PATH, "chunk-manifest.json"),
                      (CURRENT_DRAFT_PATH, "current-draft.jsonl"),
                      (V208 / "translation-equivalence-policy.md",
                       "translation-equivalence-policy.md"),
                      (V208 / "translation-equivalence-policy-ledger.jsonl",
                       "translation-equivalence-policy-ledger.jsonl")):
        shutil.copy2(src, tmp_path / name)
    return tmp_path


def _run(tmp_path, out_name="out"):
    out = tmp_path / out_name
    result = dp.run(
        out_dir=out,
        candidate_dir=tmp_path / "v211",
        review_dir=tmp_path / "v211" / "targeted-re-review",
        v210_dir=tmp_path / "v210",
        chunks_path=tmp_path / "chunks.jsonl",
        chunk_manifest_path=tmp_path / "chunk-manifest.json",
        current_draft_path=tmp_path / "current-draft.jsonl",
        trans_policy_path=tmp_path / "translation-equivalence-policy.md",
        trans_ledger_path=tmp_path / "translation-equivalence-policy-ledger.jsonl",
    )
    return result, out


def _tamper_manifest(path: Path, mutate) -> None:
    data = json.loads(path.read_text(encoding="utf-8"))
    mutate(data)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=1,
                               sort_keys=True) + "\n",
                    encoding="utf-8", newline="\n")


def _tamper_jsonl(path: Path, mutate_rows) -> None:
    """Rewrite a compact jsonl; the mutation lambda's return value is used."""
    rows = [json.loads(line) for line in
            path.read_text(encoding="utf-8").splitlines() if line.strip()]
    rows = mutate_rows(rows)
    text = "".join(
        json.dumps(r, ensure_ascii=False, sort_keys=True,
                   separators=(",", ":")) + "\n" for r in rows)
    path.write_text(text, encoding="utf-8", newline="\n")


def _sha256(path: Path) -> str:
    import hashlib
    return hashlib.sha256(path.read_bytes()).hexdigest()


# ── module constants / target derivation ────────────────────────────────

def test_constants():
    assert dp.GATE_OK == "OWNER_DECISION_PACK_OK"
    assert dp.EXPECTED_TARGET_COUNT == 22
    assert dp.EXPECTED_CASE_COUNT == 136
    assert dp.EXPECTED_EVIDENCE_COUNT == 149
    assert dp.EXCLUDED_CASE_ID == "en-048"
    assert dp.ERROR_CASES == tuple(EXPECTED_ERROR_IDS)
    assert dp.REJECT_CASE_IDS == tuple(EXPECTED_REJECT_IDS)
    assert len(dp.OUTPUT_FILES) == 8
    assert "manifest.json" in dp.OUTPUT_FILES
    assert "OWNER_DECISION_GUIDE.md" in dp.OUTPUT_FILES


def test_real_input_paths_exist():
    assert (V211 / "manifest.json").is_file()
    assert (V211 / "targeted-re-review" / "manifest.json").is_file()
    assert (V211 / "targeted-re-review" /
            "targeted-review-results.jsonl").is_file()
    assert (V211 / "targeted-re-review" /
            "targeted-review-issues.jsonl").is_file()
    assert CHUNKS_PATH.is_file()


def test_derive_target_cases_is_exact(inputs):
    target = dp.derive_target_cases(
        review_dir=inputs / "v210" / "automated-review")
    assert target == EXPECTED_TARGET_IDS
    assert len(target) == 22
    assert "en-048" not in target
    assert set(dp.ERROR_CASES) <= set(target)
    assert len(set(target)) == len(target)


def test_template_is_union_of_rejects_and_errors(inputs):
    triage = inputs / "v210" / "automated-review" / "coherence-reject-triage"
    template = [json.loads(l) for l in
                (triage / "owner-decision-template.jsonl").read_text(
                    encoding="utf-8").splitlines()]
    rejects = [json.loads(l) for l in
               (triage / "reject-root-cause-triage.jsonl").read_text(
                   encoding="utf-8").splitlines()]
    errors = [json.loads(l) for l in
              (triage / "review-coherence-errors.jsonl").read_text(
                  encoding="utf-8").splitlines()]
    assert len(template) == 23
    assert len(rejects) == 19
    assert len(errors) == 4
    reject_set = {r["case_id"] for r in rejects}
    error_set = {r["case_id"] for r in errors}
    assert reject_set == {r["case_id"] for r in template} - error_set
    assert not (reject_set & error_set)


# ── successful build ────────────────────────────────────────────────────

def test_preflight_passes_on_real_inputs(inputs):
    checks = dp.preflight(
        candidate_dir=inputs / "v211",
        review_dir=inputs / "v211" / "targeted-re-review",
        v210_dir=inputs / "v210",
        chunks_path=inputs / "chunks.jsonl",
        chunk_manifest_path=inputs / "chunk-manifest.json",
        current_draft_path=inputs / "current-draft.jsonl",
        trans_policy_path=inputs / "translation-equivalence-policy.md",
        trans_ledger_path=inputs / "translation-equivalence-policy-ledger.jsonl",
    )
    assert checks["case_count_ok"] and checks["evidence_count_ok"]
    assert checks["strict_covered"] == checks["strict_passed"] == 149
    assert checks["target_set"] == EXPECTED_TARGET_IDS


def test_run_builds_8_files(inputs):
    result, out = _run(inputs)
    assert result["gate"] == dp.GATE_OK
    assert set(p.name for p in out.iterdir()) == set(dp.OUTPUT_FILES)
    for name in dp.OUTPUT_FILES:
        assert (out / name).stat().st_size > 0


def test_manifest_self_hash_and_output_shas(inputs):
    result, out = _run(inputs)
    manifest = json.loads((out / "manifest.json").read_text(encoding="utf-8"))
    assert dp._verify_self_hash(manifest)
    for name, digest in manifest["outputs"].items():
        assert _sha256(out / name) == digest


def test_manifest_inputs_match_disk(inputs):
    _, out = _run(inputs)
    manifest = json.loads((out / "manifest.json").read_text(encoding="utf-8"))
    paths = {
        "candidate-manifest.json": inputs / "v211" / "manifest.json",
        "candidate-draft-after.jsonl": inputs / "v211" / "draft-after.jsonl",
        "candidate-evidence-after.jsonl": inputs / "v211" / "evidence-after.jsonl",
        "candidate-evidence-before.jsonl": inputs / "v211" / "evidence-before.jsonl",
        "review-manifest.json": inputs / "v211" / "targeted-re-review" / "manifest.json",
        "targeted-review-results.jsonl": inputs / "v211" / "targeted-re-review" / "targeted-review-results.jsonl",
        "targeted-review-issues.jsonl": inputs / "v211" / "targeted-re-review" / "targeted-review-issues.jsonl",
        "v210-draft-after.jsonl": inputs / "v210" / "draft-after.jsonl",
        "v210-evidence-after.jsonl": inputs / "v210" / "evidence-after.jsonl",
        "chunks.jsonl": inputs / "chunks.jsonl",
    }
    for name, path in paths.items():
        assert manifest["inputs"][name] == _sha256(path), name


def test_persistent_contract_errors_rows(inputs):
    _, out = _run(inputs)
    rows = [json.loads(l) for l in
            (out / "persistent-contract-errors.jsonl").read_text(
                encoding="utf-8").splitlines()]
    assert [r["case_id"] for r in rows] == EXPECTED_ERROR_IDS
    for row in rows:
        assert row["kind"] == "persistent_model_output_contract_inconsistency"
        assert row["expected_decision_from_local_contract"] == "confirmed"
        assert row["rewritten"] is False
        assert row["original_response_available"] is False
        assert row.get("original_response_sha256") is None
        assert row.get("original_payload_sha256") is None
        assert "original_error_text" in row and row["original_error_text"]
        assert "contract_expectation_note" in row
        assert "recommended_owner_routes" in row
        assert row["case_id"] in ("en-052", "mixed-030", "mixed-033", "zh-040")


def test_error_rows_do_not_fabricate_missing_content(inputs):
    """Missing original response/payload SHAs stay absent (no fabrication)."""
    _, out = _run(inputs)
    for name in ("persistent-contract-errors.jsonl",
                 "owner-decision-template.jsonl"):
        for line in (out / name).read_text(encoding="utf-8").splitlines():
            row = json.loads(line)
            if row["case_id"] not in EXPECTED_ERROR_IDS:
                continue
            assert "response_sha256" not in row
            assert "payload_sha256" not in row
            assert row["kind"] == "persistent_model_output_contract_inconsistency"


def test_stable_reject_rows(inputs):
    _, out = _run(inputs)
    rows = [json.loads(l) for l in
            (out / "stable-reject-root-cause-triage.jsonl").read_text(
                encoding="utf-8").splitlines()]
    assert [r["case_id"] for r in rows] == EXPECTED_REJECT_IDS
    for row in rows:
        assert row["kind"] == "reject"
        assert row["targeted_review_rationale"]["model_output"] is True
        assert row["targeted_review_rationale"]["text"]
        assert row["targeted_review_decision"] == "reject"
        assert row["targeted_review_response_sha256"]
        assert row["answer_point_relations"]
        assert row["case_classification"] in (
            "exact", "partial", "same_source", "translation", "no_direct")
        assert row["v210_triage_lineage"]["lineage_only"] is True
        assert row["recommended_action"]
        assert row["decision_options"]
        assert row["multi_turn_or_ref_dependency"] is not None


def test_reject_rows_mechanical_relation_fields(inputs):
    _, out = _run(inputs)
    rows = {json.loads(l)["case_id"]: json.loads(l) for l in
            (out / "stable-reject-root-cause-triage.jsonl").read_text(
                encoding="utf-8").splitlines()}
    for row in rows.values():
        for rel in row["answer_point_relations"]:
            assert "answer_point_index" in rel
            assert "answer_point_text" in rel
            assert rel["classification"] in (
                "exact", "partial", "same_source", "translation", "no_direct")
            assert "mechanic_proof" in rel
            if rel["classification"] == "same_source":
                cand = rel["same_source_candidate"]
                assert cand["source_id"] and cand["chunk_id"]
                assert cand["start"] < cand["end"]
                assert cand["unique"] is True
                assert cand["overlaps_existing"] is False


def test_reject_classification_distribution(inputs):
    _, out = _run(inputs)
    rows = {json.loads(l)["case_id"]: json.loads(l) for l in
            (out / "stable-reject-root-cause-triage.jsonl").read_text(
                encoding="utf-8").splitlines()}
    actual = {cid: row["case_classification"] for cid, row in rows.items()}
    assert actual == CASE_CLASSIFICATION_EXPECTED
    from collections import Counter
    counter = Counter(actual.values())
    assert dict(counter) == {"exact": 7, "partial": 7, "translation": 4}
    assert counter["same_source"] == 0 and counter["no_direct"] == 0


def test_answer_point_classification_counts(inputs):
    _, out = _run(inputs)
    from collections import Counter
    counts = Counter()
    for line in (out / "stable-reject-root-cause-triage.jsonl").read_text(
            encoding="utf-8").splitlines():
        row = json.loads(line)
        for rel in row["answer_point_relations"]:
            counts[rel["classification"]] += 1
    assert dict(counts) == {k: v for k, v in
                            AP_CLASSIFICATION_COUNTS_EXPECTED.items()
                            if v}
    assert sum(counts.values()) == 27


def test_owner_template_rows_empty_owner_fields(inputs):
    _, out = _run(inputs)
    rows = [json.loads(l) for l in
            (out / "owner-decision-template.jsonl").read_text(
                encoding="utf-8").splitlines()]
    assert len(rows) == 22
    assert [r["case_id"] for r in rows] == EXPECTED_TARGET_IDS
    for row in rows:
        assert row["owner_decision"] == ""
        assert row["owner_reviewer"] == ""
        assert row["owner_notes"] == ""
        assert row["recommended_action"]
        assert row["decision_options"]
        assert row["risk_summary"]
        assert row["evidence_summary"]
        assert row["kind"] in ("reject",
                               "persistent_model_output_contract_inconsistency")


def test_data_quality_report_five_dims(inputs):
    _, out = _run(inputs)
    dq = json.loads((out / "data-quality-report.json").read_text(
        encoding="utf-8"))
    for dim in ("completeness", "uniqueness", "referential_integrity",
                "continuity", "consistency"):
        assert dim in dq
        assert dq[dim]["status"] == "ok"
    assert dq["skill_note"]


def test_manifest_counts_and_metadata(inputs):
    _, out = _run(inputs)
    manifest = json.loads((out / "manifest.json").read_text(encoding="utf-8"))
    assert manifest["counts"] == {
        "case_count": 22, "reject": 18, "errors": 4,
        "classification_exact": 7, "classification_partial": 7,
        "classification_translation": 4, "classification_same_source": 0,
        "classification_no_direct": 0,
        "template_rows": 22,
    }
    assert manifest["target_set"] == EXPECTED_TARGET_IDS
    assert manifest["metadata"] == {
        "revision_status": "CANDIDATE",
        "activation_blocked": True,
        "human_reviewed": False,
        "overlay_generated": False,
        "split_reseal_required": True,
        "v2_1_entered": False,
    }
    assert manifest["declarations"]["llm_called"] is False
    assert manifest["declarations"]["network_used"] is False
    assert manifest["declarations"]["read_only"] is True
    assert manifest["declarations"]["overlay_generated"] is False
    assert manifest["declarations"]["split_created"] is False
    assert manifest["declarations"]["v2_1_entered"] is False
    assert manifest["reviewed_revision"] == V211.name
    assert manifest["reviewed_revision_manifest_sha256"] == _sha256(
        inputs / "v211" / "manifest.json")
    assert manifest["reviewed_review_manifest_sha256"] == _sha256(
        inputs / "v211" / "targeted-re-review" / "manifest.json")


def test_reports_exist_and_reference_boundaries(inputs):
    _, out = _run(inputs)
    report = (out / "decision-pack-report.md").read_text(encoding="utf-8")
    guide = (out / "OWNER_DECISION_GUIDE.md").read_text(encoding="utf-8")
    assert "OWNER_DECISION_PACK_OK" in report
    assert "TARGETED_REVIEW_BLOCKED" in report
    assert "activation-blocked" in report
    for marker in ("overlay", "active", "split", "locked", "v2.1"):
        assert marker in report  # 明确声明未生成
    assert "read-only" in guide or "只读" in guide


def test_inputs_unchanged_after_build(inputs):
    before = {str(p.relative_to(inputs)): _sha256(p) for p in
              inputs.rglob("*") if p.is_file()}
    _run(inputs)
    after = {str(p.relative_to(inputs)): _sha256(p) for p in
             inputs.rglob("*") if p.is_file() and "out" not in p.parts}
    assert before == after


def test_double_build_byte_identical(inputs):
    _, out1 = _run(inputs, out_name="out1")
    _, out2 = _run(inputs, out_name="out2")
    for name in dp.OUTPUT_FILES:
        assert (out1 / name).read_bytes() == (out2 / name).read_bytes(), name


def test_out_dir_exists_fails(inputs):
    out = inputs / "out"
    out.mkdir()
    with pytest.raises(dp.DecisionPackError):
        _run(inputs)


def test_no_forbidden_artifacts_in_output(inputs):
    _, out = _run(inputs)
    for name in dp.OUTPUT_FILES:
        low = name.lower()
        for marker in ("overlay", "active", "split", "locked", "v2.1"):
            assert marker not in low, name
    manifest = json.loads((out / "manifest.json").read_text(encoding="utf-8"))
    for key in ("overlay_generated", "active_created", "split_created",
                "locked_created", "v2_1_entered"):
        assert manifest["declarations"][key] is False, key


# ── fail-closed preflight ───────────────────────────────────────────────

def _assert_fail_closed(tmp_path, mutation, out_name="out"):
    mutation()
    out = tmp_path / out_name
    with pytest.raises(dp.DecisionPackError):
        _run(tmp_path, out_name=out_name)
    assert not out.exists()


def test_fail_closed_candidate_manifest_tampered(inputs):
    def mutate():
        _tamper_manifest(inputs / "v211" / "manifest.json",
                         lambda d: d.update({"gate_verdict": "TAMPERED"}))
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_candidate_manifest_output_sha_tampered(inputs):
    def mutate():
        _tamper_manifest(inputs / "v211" / "manifest.json",
                         lambda d: d["outputs"].update(
                             {"draft-after.jsonl": "0" * 64}))
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_candidate_manifest_input_sha_tampered(inputs):
    def mutate():
        _tamper_manifest(inputs / "v211" / "manifest.json",
                         lambda d: d["inputs"].update(
                             {"chunks.jsonl": "0" * 64}))
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_review_manifest_tampered(inputs):
    def mutate():
        _tamper_manifest(
            inputs / "v211" / "targeted-re-review" / "manifest.json",
            lambda d: d.update({"gate_verdict": "TARGETED_REVIEW_OK"}))
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_review_manifest_count_tampered(inputs):
    def mutate():
        _tamper_manifest(
            inputs / "v211" / "targeted-re-review" / "manifest.json",
            lambda d: d["counts"].update({"reject": 17}))
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_results_conservation_broken(inputs):
    """A reject flipped to confirmed breaks 22 = 18 + 4 conservation."""
    def mutate():
        _tamper_jsonl(inputs / "v211" / "targeted-re-review" /
                      "targeted-review-results.jsonl",
                      lambda rows: [dict(r, decision="confirmed")
                                    if r["case_id"] == "en-040" else r
                                    for r in rows])
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_results_row_removed(inputs):
    def mutate():
        _tamper_jsonl(inputs / "v211" / "targeted-re-review" /
                      "targeted-review-results.jsonl",
                      lambda rows: [r for r in rows
                                    if r["case_id"] != "zh-058"])
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_issues_row_removed(inputs):
    def mutate():
        _tamper_jsonl(inputs / "v211" / "targeted-re-review" /
                      "targeted-review-issues.jsonl",
                      lambda rows: [r for r in rows
                                    if r["case_id"] != "en-040"])
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_issues_error_fabricated_sha(inputs):
    """Error rows carrying a fabricated response_sha256 must fail closed."""
    def mutate():
        _tamper_jsonl(inputs / "v211" / "targeted-re-review" /
                      "targeted-review-issues.jsonl",
                      lambda rows: [dict(r, response_sha256="0" * 64)
                                    if r["kind"] == "error" else r
                                    for r in rows])
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_draft_not_identical_to_v210(inputs):
    def mutate():
        _tamper_jsonl(inputs / "v210" / "draft-after.jsonl",
                      lambda rows: rows[:-1])
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_evidence_delta_drift(inputs):
    """Deleting the authorised en-048 row breaks 148 → 149 delta."""
    def mutate():
        _tamper_jsonl(inputs / "v211" / "evidence-after.jsonl",
                      lambda rows: [r for r in rows
                                    if not (r["case_id"] == "en-048"
                                            and r["snippet"] == "functions")])
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_chunks_tampered(inputs):
    def mutate():
        path = inputs / "chunks.jsonl"
        _tamper_jsonl(path, lambda rows: [
            dict(r, text=r["text"] + " ")
            if r["chunk_id"] == "761b22915b5e_chunk_14" else r
            for r in rows])
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_forbidden_artifact(inputs):
    def mutate():
        (inputs / "v211" / "overlay-probe.json").write_text(
            "{}", encoding="utf-8", newline="\n")
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_forbidden_artifact_in_review_tree(inputs):
    def mutate():
        (inputs / "v211" / "targeted-re-review" / "active-config.json").write_text(
            "{}", encoding="utf-8", newline="\n")
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_current_draft_tampered(inputs):
    def mutate():
        _tamper_jsonl(inputs / "current-draft.jsonl",
                      lambda rows: rows[:-1])
    _assert_fail_closed(inputs, mutate)


def test_fail_closed_owner_template_target_set_drift(inputs):
    """Triage owner template must stay 23 rows / 23 unique case ids."""
    def mutate():
        _tamper_jsonl(inputs / "v210" / "automated-review" /
                      "coherence-reject-triage" /
                      "owner-decision-template.jsonl",
                      lambda rows: rows[:-1])
    _assert_fail_closed(inputs, mutate)


# ── mechanical classifier unit tests ────────────────────────────────────

def test_same_source_candidate_is_mechanical(inputs):
    """en-048's authorised candidate ('functions' in chunk_14) classifies
    same_source when passed as an answer point without evidence overlap."""
    chunks = dp._load_chunks(inputs / "chunks.jsonl")
    chunk = chunks["761b22915b5e_chunk_14"]
    rel = dp._classify_answer_point(
        "functions",
        evidence_rows=[],  # no evidence → no overlap
        chunks=chunks,
        relevant_source_ids=["postgresql-tutorial.md"])
    assert rel["classification"] == "same_source"
    cand = rel["same_source_candidate"]
    assert cand["chunk_id"] == "761b22915b5e_chunk_14"
    assert (cand["unicode_start"], cand["unicode_end"]) == (769, 778)
    assert cand["raw_span"] == "functions"
    assert cand["unique"] is True
    assert cand["overlaps_existing"] is False
    assert chunk["text"][cand["unicode_start"]:cand["unicode_end"]] == "functions"


def test_exact_and_translation_classifications(inputs):
    chunks = dp._load_chunks(inputs / "chunks.jsonl")
    # zh answer point vs en evidence with shared tokens → translation
    rel = dp._classify_answer_point(
        "SQLite 语法清单列出 begin-stmt / commit-stmt / rollback-stmt 等事务语句",
        evidence_rows=[
            {"raw_evidence_span":
             "begin-stmt and commit-stmt and rollback-stmt are listed"},
        ],
        chunks=chunks,
        relevant_source_ids=["sqlite-lang.md"])
    assert rel["classification"] == "translation"
    # exact: answer point directly contained in an evidence span
    rel2 = dp._classify_answer_point(
        "stdlib 是标准库（standard library）的缩写",
        evidence_rows=[
            {"raw_evidence_span":
             "stdlib -- 标准库¶ standard library 的缩写。"},
        ],
        chunks=chunks,
        relevant_source_ids=["python-glossary-zh.md"])
    assert rel2["classification"] in ("exact", "partial")


def test_lcs_threshold_is_max_3_10pct(inputs):
    assert dp._lcs("abcdefgh", "abxdefgh") == 7
    thr = dp._partial_threshold(len("short"), len("longer text here"))
    assert thr == max(3, int(0.10 * min(len("short"), len("longer text here"))))


# ── determinism of the script itself ────────────────────────────────────

def test_py_compile():
    subprocess.run([sys.executable, "-m", "py_compile",
                    str(ROOT / "scripts" /
                        "corpus_v2_v211_targeted_remaining22_decision_pack.py")],
                   check=True, capture_output=True)
