"""Tests for src.retrieval_ablation — Phase 6-C1 deterministic ablation strategies.

The candidate strategy (``mechanical-clause-rrf``) must be:
- purely mechanical: variants are literal substrings of the original query
  (full query always first, deduped, non-empty, capped), never generated by
  an LLM and never requiring network access;
- deterministic and stable: same input → same variants; fusion stable with a
  deterministic ``chunk_id`` tie-break when combining ≥2 variants; a single
  variant is passed through verbatim (preserving the product's stable order,
  so the single-query arm is byte-identical to the existing baseline runner);
- fail-closed: unknown / invalid strategy raises ValueError before any
  retrieval, never silently falls back;
- provenance-preserving: every fused result keeps its chunk_id, source_id,
  source_path, source_name and the per-variant ranks/scores it came from;
- opt-in only: nothing here is imported or called by the default product
  retrieval path.
"""

from __future__ import annotations

import sys

import pytest

from src.retrieval_ablation import (
    STRATEGIES,
    _per_case_metrics,
    fuse_variant_lists,
    generate_query_variants,
    get_strategy,
    retrieve_variant_lists,
    run_candidate_retrieval,
)

# ── fake retrieval doubles ────────────────────────────────────────────

META = [
    {"chunk_id": f"c{i:02d}", "source_id": f"src-{i:02d}",
     "source_name": f"name-{i:02d}", "source_path": f"path-{i:02d}.md"}
    for i in range(12)
]
DOCS = [f"document {i} content about topic-{i}" for i in range(12)]
FAKE_INDEX = {"model": None, "collection": None, "bm25": None,
              "documents": DOCS, "metadatas": META}


def _fake_retrieve(query, model, collection, bm25, documents, metadatas, k=70):
    """Deterministic fake: chunks whose doc contains the query's first token
    come first, then the rest in index order (product call signature)."""
    tokens = query.lower().split()
    key = tokens[0] if tokens else ""
    def order(i):
        return 0 if key and key in DOCS[i].lower() else 1
    idx = sorted(range(len(documents)), key=lambda i: (order(i), i))
    return idx, [documents[i] for i in idx], [1.0 / (r + 1) for r in range(len(idx))]


def _run_baseline_rows(cases, index, retrieve_fn):
    """bl6a.run_retrieval 的等价物（不导入 scripts，避免脚本级依赖）。"""
    rows = []
    for case in cases:
        indices, _, scores = retrieve_fn(
            query=case["query"], model=None, collection=None, bm25=None,
            documents=index["documents"], metadatas=index["metadatas"])
        metas = index["metadatas"]
        retrieved_chunk_ids = [metas[i]["chunk_id"] for i in indices]
        retrieved_source_ids = []
        seen = set()
        for i in indices:
            source = metas[i].get("source_name") or metas[i].get("source")
            if source and source not in seen:
                seen.add(source)
                retrieved_source_ids.append(source)
        rows.append({
            "case_id": case["case_id"],
            "query": case["query"],
            "query_type": case["query_type"],
            "language": case["language"],
            "should_refuse": case["should_refuse"],
            "relevant_chunk_ids": case["relevant_chunk_ids"],
            "relevant_source_ids": case["relevant_source_ids"],
            "retrieved_chunk_ids": retrieved_chunk_ids,
            "retrieved_source_ids": retrieved_source_ids,
            "scores": [float(s) for s in scores],
            "metrics": (
                _per_case_metrics(
                    retrieved_chunk_ids, set(case["relevant_chunk_ids"]),
                    retrieved_source_ids, set(case["relevant_source_ids"]))
                if case["relevant_chunk_ids"] else {}),
        })
    return rows


# ── Group 1: variant generation ───────────────────────────────────────

def test_variants_full_query_first_and_literal_substrings():
    q = "比较 A 和 B 的区别。B 在哪个章节？"
    variants = generate_query_variants(q)
    assert variants[0] == q
    for v in variants:
        assert v  # 非空
        assert v in q  # 字面子串，绝不生成新语义文本


def test_variants_deterministic_and_dedupe():
    q = "A。B。A。C！D？"
    v1 = generate_query_variants(q)
    v2 = generate_query_variants(q)
    assert v1 == v2  # 确定性
    assert len(v1) == len(set(v1))  # 去重
    # 重复分句只保留一次（首次出现位置）
    assert v1.count("A") == 1


def test_variants_split_on_strong_clauses():
    q = "第一个问题是什么？第二个问题如何解决。第三个！"
    variants = generate_query_variants(q)
    assert variants[0] == q
    assert "第一个问题是什么" in variants
    assert "第二个问题如何解决" in variants
    assert "第三个" in variants


def test_variants_weak_split_only_for_long_clauses():
    q = ("这篇文档介绍了数据库的创建、查询和索引维护，" * 3 + "，这段足够长。")
    variants = generate_query_variants(q, weak_split_threshold=60)
    assert variants[0] == q
    # 弱分句产出片段也必须全为字面子串
    for v in variants:
        assert v in q


def test_variants_language_boundary_split():
    q = "LLMs for mobility 这篇文章的作者都属于什么学校？"
    variants = generate_query_variants(q)
    assert variants[0] == q
    assert "LLMs for mobility" in variants
    assert "这篇文章的作者都属于什么学校" in variants


def test_variants_capped_at_max():
    q = "。".join(f"问题{i}" for i in range(30)) + "。"
    variants = generate_query_variants(q, max_variants=8)
    assert len(variants) <= 8
    assert variants[0] == q


def test_variants_empty_query_fail_closed():
    with pytest.raises(ValueError):
        generate_query_variants("   ")


def test_variants_generation_never_imports_llm_or_network():
    # 记录调用前已导入模块，生成/融合路径不得新增任何 LLM/网络导入
    before = set(sys.modules)
    generate_query_variants("A。B？")
    fuse_variant_lists([
        {"variant": "A", "chunk_ids": ["c00"], "scores": [1.0],
         "ranks": {"c00": 1}},
        {"variant": "B", "chunk_ids": ["c01"], "scores": [1.0],
         "ranks": {"c01": 1}},
    ])
    added = set(sys.modules) - before
    assert not added & {
        "src.llm_gateway", "src.rag_query_decomposer", "src.rag_query_rewriter",
        "requests", "urllib", "urllib.request", "http.client", "socket",
    }, f"variant/fusion path imported forbidden modules: {sorted(added)}"


# ── Group 2: fusion ───────────────────────────────────────────────────

def test_fusion_stable_and_tie_break_by_chunk_id():
    per_variant = [
        {"variant": "Q", "chunk_ids": ["c05", "c03", "c01"],
         "scores": [1.0, 0.8, 0.6], "ranks": {"c05": 1, "c03": 2, "c01": 3}},
        {"variant": "clause1", "chunk_ids": ["c03", "c05"],
         "scores": [1.0, 0.8], "ranks": {"c03": 1, "c05": 2}},
    ]
    out1 = fuse_variant_lists(per_variant, rrf_k=60)
    out2 = fuse_variant_lists(per_variant, rrf_k=60)
    assert out1["chunk_ids"] == out2["chunk_ids"]  # 相同输入 → 相同输出
    # c05(rank1+2) 与 c03(rank2+1) 的 RRF 和相等 → tie-break 按 chunk_id 升序
    scores = dict(zip(out1["chunk_ids"], out1["scores"]))
    assert abs(scores["c05"] - scores["c03"]) < 1e-12
    assert out1["chunk_ids"].index("c03") < out1["chunk_ids"].index("c05")
    assert out1["chunk_ids"][-1] == "c01"  # 单独 rank3，和最小，排最后


def test_fusion_dedupes_and_single_variant_passthrough():
    per_variant = [
        {"variant": "Q", "chunk_ids": ["c00", "c01", "c02"],
         "scores": [1.0, 0.9, 0.8], "ranks": {"c00": 1, "c01": 2, "c02": 3}},
        {"variant": "c1", "chunk_ids": ["c02", "c00"],
         "scores": [1.0, 0.9], "ranks": {"c02": 1, "c00": 2}},
    ]
    out = fuse_variant_lists(per_variant, rrf_k=60)
    assert len(out["chunk_ids"]) == len(set(out["chunk_ids"]))  # 无重复 chunk id
    assert set(out["chunk_ids"]) == {"c00", "c01", "c02"}
    # 单 variant 原样透传（保持产品稳定排序，不重排 tie）
    single = fuse_variant_lists([per_variant[0]], rrf_k=60)
    assert single["chunk_ids"] == per_variant[0]["chunk_ids"]
    assert single["scores"] == per_variant[0]["scores"]


def test_fusion_provenance_records_variants():
    per_variant = [
        {"variant": "Q", "chunk_ids": ["c00", "c01"],
         "scores": [1.0, 0.9], "ranks": {"c00": 1, "c01": 2}},
        {"variant": "c1", "chunk_ids": ["c01"],
         "scores": [1.0], "ranks": {"c01": 1}},
    ]
    out = fuse_variant_lists(per_variant, rrf_k=60)
    prov = {p["chunk_id"]: p for p in out["provenance"]}
    assert prov["c00"]["variant_ranks"] == [{"variant_index": 0, "rank": 1}]
    assert {r["variant_index"] for r in prov["c01"]["variant_ranks"]} == {0, 1}


# ── Group 3: strategy registry (fail-closed) ──────────────────────────

def test_strategy_registry_contents():
    assert set(STRATEGIES) == {"single-query", "mechanical-clause-rrf"}
    spec = get_strategy("mechanical-clause-rrf")
    assert spec["name"] == "mechanical-clause-rrf"
    assert spec["version"] == "1.0"
    assert spec["no_llm"] is True
    assert get_strategy("single-query")["name"] == "single-query"


def test_get_strategy_unknown_fail_closed():
    with pytest.raises(ValueError):
        get_strategy("does-not-exist")


def test_run_candidate_unknown_strategy_fail_closed_zero_retrieval(monkeypatch):
    calls = []

    def _forbid(*args, **kwargs):
        calls.append(1)
        raise AssertionError("must not retrieve for unknown strategy")

    monkeypatch.setattr("src.retrieval_ablation.retrieve_variant_lists",
                        _forbid)
    with pytest.raises(ValueError):
        run_candidate_retrieval(
            [{"case_id": "c1", "query": "A", "query_type": "single_fact",
              "language": "en", "should_refuse": False,
              "relevant_chunk_ids": [], "relevant_source_ids": []}],
            FAKE_INDEX, strategy="bogus",
        )
    assert calls == []  # 未知策略在检索之前就失败


# ── Group 4: runner against the baseline shape ────────────────────────

def test_single_query_strategy_matches_baseline_rows_byte_identical():
    cases = [
        {"case_id": "en-001", "query": "compare topic-3 and topic-5",
         "query_type": "cross_document", "language": "en",
         "should_refuse": False,
         "relevant_chunk_ids": ["c03", "c05"],
         "relevant_source_ids": ["name-03"]},
        {"case_id": "zh-002", "query": "无真值观察", "query_type": "no_answer",
         "language": "zh", "should_refuse": True,
         "relevant_chunk_ids": [], "relevant_source_ids": []},
    ]
    baseline = _run_baseline_rows(cases, FAKE_INDEX, _fake_retrieve)
    candidate = run_candidate_retrieval(
        cases, FAKE_INDEX, strategy="single-query", retrieve_fn=_fake_retrieve)
    assert len(candidate) == len(baseline) == 2
    for b, c in zip(baseline, candidate):
        for key in b:
            assert c[key] == b[key], f"field {key} drifted in {c['case_id']}"
        assert c["strategy"] == "single-query"
        assert c["variants"] == [c["query"]]


def test_candidate_rows_unique_chunk_ids_full_metadata_and_provenance():
    cases = [
        {"case_id": "cd-001",
         "query": "Compare topic-3 and topic-5. 哪个更常用？",
         "query_type": "cross_document", "language": "mixed",
         "should_refuse": False,
         "relevant_chunk_ids": ["c03", "c05"],
         "relevant_source_ids": ["name-03"]},
    ]
    rows = run_candidate_retrieval(
        cases, FAKE_INDEX, strategy="mechanical-clause-rrf",
        retrieve_fn=_fake_retrieve)
    row = rows[0]
    # 无重复 chunk id
    assert len(row["retrieved_chunk_ids"]) == len(set(row["retrieved_chunk_ids"]))
    # variants：完整 query 优先 + 全为字面子串
    assert row["variants"][0] == row["query"]
    for v in row["variants"]:
        assert v in row["query"]
    # provenance：每个结果保留 source/citation metadata + variant 来源
    assert row["fusion"]["tie_break"] == "chunk_id_asc"
    by_id = {p["chunk_id"]: p for p in row["provenance"]}
    for cid in row["retrieved_chunk_ids"][:5]:
        p = by_id[cid]
        assert p["source_id"]
        assert p["source_path"]
        assert p["source_name"]
        assert p["variant_ranks"]
    # retrieved_source_ids 与 baseline 同构（source_name 首现序）
    assert row["retrieved_source_ids"]
    # 指标存在（有真值时）
    assert row["metrics"]["recall@5"] >= 0.0


def test_candidate_runner_preserves_query_type_grouping_fields():
    cases = [
        {"case_id": "cd-002", "query": "A。B？", "query_type": "cross_document",
         "language": "en", "should_refuse": False,
         "relevant_chunk_ids": ["c00"], "relevant_source_ids": ["name-00"]},
    ]
    rows = run_candidate_retrieval(
        cases, FAKE_INDEX, strategy="mechanical-clause-rrf",
        retrieve_fn=_fake_retrieve)
    row = rows[0]
    assert row["query_type"] == "cross_document"
    assert row["language"] == "en"
    assert row["should_refuse"] is False
    assert row["relevant_chunk_ids"] == ["c00"]
    assert "strategy_version" in row
