"""Corpus v2 annotation content — part B (english docs: py-en, sqlite, pg, rust, rfc, nodejs)."""

CASES_B = {
    # ── chain multi-015 (python-tutorial-en, 3 turns) ───────────────
    "multi-015": {
        "query": "In the Python tutorial, what does the example `rgb = [\"Red\", \"Green\", \"Blue\"]; rgba = rgb` demonstrate about assignment?",
        "relevant_source_ids": ["python-tutorial-en.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-en.md",
            "chunk_id": "e564a122a7a2_chunk_14",
            "chunk_text_snippet": "rgb = [\"Red\", \"Green\", \"Blue\"] >>> rgba = rgb >>> id(rgb) == id(rgba) # they reference the same object True",
            "page": None, "section": "3.1.3 Lists",
        }],
        "relevant_chunk_ids": ["e564a122a7a2_chunk_14"],
        "acceptable_answer_points": ["simple assignment never copies data", "both names reference the same object"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-016": {
        "query": "What does appending to `rgba` do to `rgb` in that same example?",
        "relevant_source_ids": ["python-tutorial-en.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-en.md",
            "chunk_id": "e564a122a7a2_chunk_14",
            "chunk_text_snippet": ">>> rgba.append(\"Alph\") >>> rgb [\"Red\", \"Green\", \"Blue\", \"Alph\"]",
            "page": None, "section": "3.1.3 Lists",
        }],
        "relevant_chunk_ids": ["e564a122a7a2_chunk_14"],
        "acceptable_answer_points": ["rgb also changes because it is the same list object"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-017": {
        "query": "The tutorial says Python is easy to learn and powerful — where can the interpreter and standard library be obtained?",
        "relevant_source_ids": ["python-tutorial-en.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-en.md",
            "chunk_id": "e564a122a7a2_chunk_1",
            "chunk_text_snippet": "The Python interpreter and the extensive standard library are freely available in source or binary form for all major platforms from the Python website, https://www.python.org/, and may be freely distributed.",
            "page": None, "section": "Introduction",
        }],
        "relevant_chunk_ids": ["e564a122a7a2_chunk_1"],
        "acceptable_answer_points": ["freely available", "from the Python web site https://www.python.org/"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── single_fact en ─────────────────────────────────────────────
    "en-021": {
        "query": "In the tutorial, how do you reference the last character of a string `word`?",
        "relevant_source_ids": ["python-tutorial-en.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-en.md",
            "chunk_id": "e564a122a7a2_chunk_11",
            "chunk_text_snippet": "Indices may also be negative numbers, to start counting from the right:\n\n```\n>>> word[-1]  # last character\n'n'\n>>> word[-2]  # second-last character\n'o'\n>>> word[-6]\n'P'\n```",
            "page": None, "section": "3.1.2 Strings",
        }],
        "relevant_chunk_ids": ["e564a122a7a2_chunk_11"],
        "acceptable_answer_points": ["word[-1]", "negative indices count from the right"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-022": {
        "query": "Which statement in the tutorial compares an expression against a series of patterns?",
        "relevant_source_ids": ["python-tutorial-en.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-en.md",
            "chunk_id": "e564a122a7a2_chunk_26",
            "chunk_text_snippet": "## 4.7.\n```\nmatch\n```\n Statements¶\n A\n```\nmatch\n```\n statement takes an expression and compares its value to successive patterns given as one or more case blocks.",
            "page": None, "section": "4.7 match Statements",
        }],
        "relevant_chunk_ids": ["e564a122a7a2_chunk_26"],
        "acceptable_answer_points": ["match statement"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-023": {
        "query": "According to the coding style section, how many spaces are recommended for indentation?",
        "relevant_source_ids": ["python-tutorial-en.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-en.md",
            "chunk_id": "e564a122a7a2_chunk_44",
            "chunk_text_snippet": "- Use 4-space indentation, and no tabs.\n 4 spaces are a good compromise between small indentation (allows greater nesting depth) and large indentation (easier to read).",
            "page": None, "section": "4.10 Intermezzo: Coding Style",
        }],
        "relevant_chunk_ids": ["e564a122a7a2_chunk_44"],
        "acceptable_answer_points": ["4 spaces", "no tabs"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-024": {
        "query": "In SQLite, what does the phrase \"Small. Fast. Reliable.\" refer to?",
        "relevant_source_ids": ["sqlite-lang.md"],
        "relevant_chunks": [{
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_21",
            "chunk_text_snippet": "Small. Fast. Reliable.Choose any three.",
            "page": None, "section": "SQLite SQL 语言概述",
        }],
        "relevant_chunk_ids": ["8b191b241b93_chunk_21"],
        "acceptable_answer_points": ["SQLite 的标语/特点（Choose any three）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-025": {
        "query": "Which SQL statement is used to query the database in SQLite?",
        "relevant_source_ids": ["sqlite-lang.md"],
        "relevant_chunks": [{
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_24",
            "chunk_text_snippet": "The SELECT statement is used to query the database. The result of a SELECT is zero or more rows of data where each row has a fixed number of columns.",
            "page": None, "section": "SELECT",
        }],
        "relevant_chunk_ids": ["8b191b241b93_chunk_24"],
        "acceptable_answer_points": ["SELECT"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-026": {
        "query": "What is the first form of INSERT that creates one or more new rows in an existing table?",
        "relevant_source_ids": ["sqlite-lang.md"],
        "relevant_chunks": [{
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_66",
            "chunk_text_snippet": "1. INSERT INTO table VALUES(...);\nThe first form (with the \"VALUES\" keyword) creates one or more new rows in an existing table.",
            "page": None, "section": "INSERT",
        }],
        "relevant_chunk_ids": ["8b191b241b93_chunk_66"],
        "acceptable_answer_points": ["INSERT INTO table VALUES(...)"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-027": {
        "query": "In the PostgreSQL tutorial, what is the recommended way to create the first user account?",
        "relevant_source_ids": ["postgresql-tutorial.md"],
        "relevant_chunks": [{
            "source_id": "postgresql-tutorial.md",
            "chunk_id": "761b22915b5e_chunk_4",
            "chunk_text_snippet": "You will need to become the operating system user under which PostgreSQL was installed (usually postgres) to create the first user account",
            "page": None, "section": "1. Getting Started",
        }],
        "relevant_chunk_ids": ["761b22915b5e_chunk_4"],
        "acceptable_answer_points": ["become the postgres OS user", "create the first user account under the installation user"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-028": {
        "query": "What does the advanced chapter say a transactional database guarantees about updates?",
        "relevant_source_ids": ["postgresql-tutorial.md"],
        "relevant_chunks": [{
            "source_id": "postgresql-tutorial.md",
            "chunk_id": "761b22915b5e_chunk_12",
            "chunk_text_snippet": "A transactional database guarantees that all the updates made by a transaction are logged in permanent storage (i.e., on disk) before the transactio",
            "page": None, "section": "3.4 Transactions",
        }],
        "relevant_chunk_ids": ["761b22915b5e_chunk_12"],
        "acceptable_answer_points": ["updates are logged to permanent storage (disk) before the transaction completes"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-029": {
        "query": "What are the ownership rules in the Rust book?",
        "relevant_source_ids": ["rust-book-core.md"],
        "relevant_chunks": [{
            "source_id": "rust-book-core.md",
            "chunk_id": "4f9001ca8c15_chunk_37",
            "chunk_text_snippet": "### Ownership Rules\n\nFirst, let’s take a look at the ownership rules. Keep these rules in mind as we\nwork through the examples that illustrate them:",
            "page": None, "section": "4.1 What Is Ownership",
        }],
        "relevant_chunk_ids": ["4f9001ca8c15_chunk_37"],
        "acceptable_answer_points": ["每条值有唯一所有者", "所有者离开作用域时值被丢弃"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；chunk 含规则列表，答案要点以规则概括为准",
    },
    "en-030": {
        "query": "Which data type does the Rust book introduce first to illustrate ownership?",
        "relevant_source_ids": ["rust-book-core.md"],
        "relevant_chunks": [{
            "source_id": "rust-book-core.md",
            "chunk_id": "4f9001ca8c15_chunk_38",
            "chunk_text_snippet": "### The `String` Type\n\nTo illustrate the rules of ownership, we need a data type that is more complex\nthan those we covered in the [“Data Types”][data-types]<!-- ignore --> section\nof Chapter 3.",
            "page": None, "section": "4.1 What Is Ownership",
        }],
        "relevant_chunk_ids": ["4f9001ca8c15_chunk_38"],
        "acceptable_answer_points": ["String 类型"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-031": {
        "query": "Which RFC document defines the URI generic syntax?",
        "relevant_source_ids": ["rfc3986.txt"],
        "relevant_chunks": [{
            "source_id": "rfc3986.txt",
            "chunk_id": "86ef1bf559c5_chunk_6",
            "chunk_text_snippet": "1.  Introduction\n\n   A Uniform Resource Identifier (URI) provides a simple and extensible\n   means for identifying a resource.",
            "page": None, "section": "1. Introduction",
        }],
        "relevant_chunk_ids": ["86ef1bf559c5_chunk_6"],
        "acceptable_answer_points": ["RFC 3986"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-032": {
        "query": "In the Node.js fs docs, which class wraps a numeric file descriptor?",
        "relevant_source_ids": ["nodejs-fs.md"],
        "relevant_chunks": [{
            "source_id": "nodejs-fs.md",
            "chunk_id": "b9c22720dc84_chunk_15",
            "chunk_text_snippet": "#### Class:\n```\nFileHandle\n```\n#\n  Added in: v10.0.0\n A <FileHandle> object is an object wrapper for a numeric file descriptor.",
            "page": None, "section": "Class FileHandle",
        }],
        "relevant_chunk_ids": ["b9c22720dc84_chunk_15"],
        "acceptable_answer_points": ["FileHandle"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── metadata en ────────────────────────────────────────────────
    "en-033": {
        "query": "In RFC 3986, which section covers percent-encoding?",
        "relevant_source_ids": ["rfc3986.txt"],
        "relevant_chunks": [{
            "source_id": "rfc3986.txt",
            "chunk_id": "86ef1bf559c5_chunk_19",
            "chunk_text_snippet": "2.1. Percent-Encoding A percent-encoding mechanism is used to represent a data octet in a component",
            "page": None, "section": "2. Characters",
        }],
        "relevant_chunk_ids": ["86ef1bf559c5_chunk_19"],
        "acceptable_answer_points": ["section 2.1 Percent-Encoding"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-034": {
        "query": "Who are the authors of RFC 3986 listed in the document header?",
        "relevant_source_ids": ["rfc3986.txt"],
        "relevant_chunks": [{
            "source_id": "rfc3986.txt",
            "chunk_id": "86ef1bf559c5_chunk_0",
            "chunk_text_snippet": "Network Working Group T. Berners-Lee Request for Comments: 3986 W3C/MIT STD: 66 R. Fielding Updates: 1738 Day Software",
            "page": None, "section": "Header",
        }],
        "relevant_chunk_ids": ["86ef1bf559c5_chunk_0"],
        "acceptable_answer_points": ["T. Berners-Lee", "R. Fielding"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-035": {
        "query": "In the Node.js fs documentation, since which version was FileHandle added?",
        "relevant_source_ids": ["nodejs-fs.md"],
        "relevant_chunks": [{
            "source_id": "nodejs-fs.md",
            "chunk_id": "b9c22720dc84_chunk_15",
            "chunk_text_snippet": "#### Class:\n```\nFileHandle\n```\n#\n  Added in: v10.0.0",
            "page": None, "section": "Class FileHandle",
        }],
        "relevant_chunk_ids": ["b9c22720dc84_chunk_15"],
        "acceptable_answer_points": ["v10.0.0"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-036": {
        "query": "What is the default value of `highWaterMark` for the stream options in the fs docs?",
        "relevant_source_ids": ["nodejs-fs.md"],
        "relevant_chunks": [{
            "source_id": "nodejs-fs.md",
            "chunk_id": "b9c22720dc84_chunk_17",
            "chunk_text_snippet": "-\n```\nhighWaterMark\n```\n <integer> Default:\n```\n64 * 1024\n```",
            "page": None, "section": "Stream options",
        }],
        "relevant_chunk_ids": ["b9c22720dc84_chunk_17"],
        "acceptable_answer_points": ["64 * 1024 (64 KiB)"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-037": {
        "query": "Which section of the SQLite doc explains that \"Unlike most SQL databases, SQLite does not restrict the type of data that may be inserted into a column\"?",
        "relevant_source_ids": ["sqlite-lang.md"],
        "relevant_chunks": [{
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_13",
            "chunk_text_snippet": "## 3.1. Column Data Types\n Unlike most SQL databases, SQLite does not restrict the type of data that may be inserted into a column based on the columns declared type.",
            "page": None, "section": "3.1 Column Data Types",
        }],
        "relevant_chunk_ids": ["8b191b241b93_chunk_13"],
        "acceptable_answer_points": ["3.1 Column Data Types"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-038": {
        "query": "Which chapter of the PostgreSQL tutorial covers views, foreign keys and transactions?",
        "relevant_source_ids": ["postgresql-tutorial.md"],
        "relevant_chunks": [{
            "source_id": "postgresql-tutorial.md",
            "chunk_id": "761b22915b5e_chunk_8",
            "chunk_text_snippet": "# 3. Advanced Features",
            "page": None, "section": "3. Advanced Features",
        }],
        "relevant_chunk_ids": ["761b22915b5e_chunk_8"],
        "acceptable_answer_points": ["Chapter 3 Advanced Features"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-039": {
        "query": "Which section of the Rust book explains references and borrowing?",
        "relevant_source_ids": ["rust-book-core.md"],
        "relevant_chunks": [{
            "source_id": "rust-book-core.md",
            "chunk_id": "4f9001ca8c15_chunk_48",
            "chunk_text_snippet": "# 4.2 引用与借用\n\n## References and Borrowing\n\nThe issue with the tuple code in Listing 4-5 is that we have to return the\n`String` to the calling function",
            "page": None, "section": "4.2 References and Borrowing",
        }],
        "relevant_chunk_ids": ["4f9001ca8c15_chunk_48"],
        "acceptable_answer_points": ["4.2 References and Borrowing"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── mixed_intent en ─────────────────────────────────────────────
    "en-054": {
        "query": "The SQLite doc mentions rowid — in which table type is the rowid omitted?",
        "relevant_source_ids": ["sqlite-lang.md"],
        "relevant_chunks": [{
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_19",
            "chunk_text_snippet": "The rowid (and \"oid\" and \"_rowid_\") is omitted in WITHOUT ROWID tables",
            "page": None, "section": "CREATE TABLE",
        }],
        "relevant_chunk_ids": ["8b191b241b93_chunk_19"],
        "acceptable_answer_points": ["WITHOUT ROWID tables"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-055": {
        "query": "The Rust book says values are moved rather than copied in some cases — what operator creates a reference instead?",
        "relevant_source_ids": ["rust-book-core.md"],
        "relevant_chunks": [{
            "source_id": "rust-book-core.md",
            "chunk_id": "4f9001ca8c15_chunk_48",
            "chunk_text_snippet": "A reference is like a pointer in that it’s an address we can follow to access\nthe data stored at that address; that data is owned by some other variable.",
            "page": None, "section": "4.2 References and Borrowing",
        }],
        "relevant_chunk_ids": ["4f9001ca8c15_chunk_48"],
        "acceptable_answer_points": ["& 运算符（借用/引用）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-056": {
        "query": "In the fs docs, `fsPromises.cp` was no longer experimental since which version?",
        "relevant_source_ids": ["nodejs-fs.md"],
        "relevant_chunks": [{
            "source_id": "nodejs-fs.md",
            "chunk_id": "b9c22720dc84_chunk_31",
            "chunk_text_snippet": "####\n```\nfsPromises.cp(src, dest[, options])\n```\n#\n  History\n\nVersionChanges\n\n | v22.3.0  | This API is no longer experimental.",
            "page": None, "section": "fsPromises.cp",
        }],
        "relevant_chunk_ids": ["b9c22720dc84_chunk_31"],
        "acceptable_answer_points": ["v22.3.0"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-057": {
        "query": "RFC 3986 defines both `gen-delims` and `sub-delims` — which set does the character \"@\" belong to?",
        "relevant_source_ids": ["rfc3986.txt"],
        "relevant_chunks": [{
            "source_id": "rfc3986.txt",
            "chunk_id": "86ef1bf559c5_chunk_20",
            "chunk_text_snippet": "gen-delims = \":\" / \"/\" / \"?\" / \"#\" / \"[\" / \"]\" / \"@\" sub-delims = \"!\" / \"$\" / \"&\" / \"'\" / \"(\" / \")\"",
            "page": None, "section": "2.2 Reserved Characters",
        }],
        "relevant_chunk_ids": ["86ef1bf559c5_chunk_20"],
        "acceptable_answer_points": ["gen-delims"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
}
