"""Corpus v2 annotation content — part A (python-tutorial-zh + zh chain).

Each entry: id -> {query, relevant_source_ids, relevant_chunks, relevant_chunk_ids,
acceptable_answer_points, should_refuse, relevance_level, review_notes}.
LLM_ASSISTED draft annotations; chunk snippets are verbatim from chunks.jsonl.
"""

CASES_A = {
    # ── chain multi-011 (python-tutorial-zh, 4 turns) ──────────────
    "multi-011": {
        "query": "Python 教程里提到，列表和字符串这两种数据类型有什么共性？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_25",
            "chunk_text_snippet": "列表和字符串有很多共性，例如，索引和切片操作。 这两种数据类型是 序列 (参见 序列类型 --- list, tuple, range)。",
            "page": None, "section": "5.3 元组和序列",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_25"],
        "acceptable_answer_points": ["都支持索引和切片操作", "两者都是序列类型"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-012": {
        "query": "那序列解包的时候，左边变量的数量和右边元素的数量要满足什么条件？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_26",
            "chunk_text_snippet": "序列解包时，左侧变量与右侧序列元素的数量应相等",
            "page": None, "section": "5.3 元组和序列",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_26"],
        "acceptable_answer_points": ["数量应相等"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-013": {
        "query": "教程里用 fibo 模块举例，如果想用 as 给导入的模块起别名，应该怎么写？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_31",
            "chunk_text_snippet": "模块名后使用\n```\nas\n```\n 时，直接把\n```\nas\n```\n 后的名称与导入模块绑定。\n\n```\n>>> import fibo as fib\n>>> fib.fib(500)\n0 1 1 2 3 5 8 13 21 34 55 89 144 233 377\n```",
            "page": None, "section": "6.1.1 以脚本方式执行模块",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_31"],
        "acceptable_answer_points": ["使用 import fibo as fib", "用 as 后的名称绑定导入模块"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-014": {
        "query": "如果 from fibo import * 引入了不该引入的名字，教程建议怎么避免这种问题？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_31",
            "chunk_text_snippet": "这种方式会导入所有不以下划线 (\n```\n_\n```\n) 开头的名称。 大多数情况下，不要用这个功能，这种方式向解释器导入了一批未知的名称，可能会覆盖已经定义的名称。",
            "page": None, "section": "6.1.1 以脚本方式执行模块",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_31"],
        "acceptable_answer_points": ["尽量不要使用 from ... import *", "建议使用 from package import specific_submodule"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── single_fact zh ─────────────────────────────────────────────
    "zh-021": {
        "query": "教程里说，那个上次输出的表达式会被赋给哪个变量，方便做下一步计算？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_3",
            "chunk_text_snippet": "交互模式下，上次输出的表达式会赋给变量\n```\n_\n```\n。把 Python 当作计算器时，用该变量实现下一步计算更简单，例如：\n\n```\n>>> tax = 12.5 / 100\n>>> price = 100.50\n>>> price * tax\n12.5625\n>>> price + _\n113.0625\n>>> round(_, 2)\n113.06\n```",
            "page": None, "section": "3.1.1 数字",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_3"],
        "acceptable_answer_points": ["下划线 _"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；模糊提问构造（low_answerable）",
    },
    "zh-022": {
        "query": "教程里讲的这个语言，它的复数是用什么后缀表示的？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_3",
            "chunk_text_snippet": "Python 还内置支持 复数，后缀\n```\nj\n```\n 或\n```\nJ\n```\n 用于表示虚数 (例如\n```\n3+5j\n```\n)。",
            "page": None, "section": "3.1.1 数字",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_3"],
        "acceptable_answer_points": ["j 或 J"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；模糊提问构造（low_answerable）",
    },
    "zh-023": {
        "query": "教程中 range(10) 会生成几个值？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_10",
            "chunk_text_snippet": "range(10) 生成 10 个值——长度为 10 的序列的所有合法索引",
            "page": None, "section": "4.3 range() 函数",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_10"],
        "acceptable_answer_points": ["10 个值"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-024": {
        "query": "教程中 for 循环里的 else 子句在什么情况下会执行？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_11",
            "chunk_text_snippet": "如果循环在未执行\n```\nbreak\n```\n 的情况下结束，\n```\nelse\n```\n 子句将会执行。",
            "page": None, "section": "4.5 循环的 else 子句",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_11"],
        "acceptable_answer_points": ["循环未执行 break 就结束时执行"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-025": {
        "query": "Python 教程中，创建空集合应该用什么函数，而不能用花括号？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_26",
            "chunk_text_snippet": "创建空集合只能用\n```\nset()\n```\n，不能用\n```\n{}\n```\n，\n```\n{}\n```\n 创建的是空字典，下一小节介绍数据结构：字典。",
            "page": None, "section": "5.4 集合",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_26"],
        "acceptable_answer_points": ["set() 函数"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-026": {
        "query": "教程里说，从列表中删除切片可以用什么语句？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_25",
            "chunk_text_snippet": "del 语句还可被用来从列表移除切片或清空整个列表",
            "page": None, "section": "5.2 del 语句",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_25"],
        "acceptable_answer_points": ["del 语句"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-027": {
        "query": "教程中表达式内部赋值必须显式使用哪个运算符，以避免和 C 语言混淆？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_29",
            "chunk_text_snippet": "在表达式内部赋值必须显式使用 海象运算符\n```\n:=\n```\n。 这避免了 C 程序中常见的问题：要在表达式中写\n```\n==\n```\n 时，却写成了\n```\n=\n```\n。",
            "page": None, "section": "5.7 更多流程控制工具",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_29"],
        "acceptable_answer_points": ["海象运算符 :="],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-028": {
        "query": "教程里那个关于文件的例子中，用 open 打开文件时推荐的编码参数值是什么？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_43",
            "chunk_text_snippet": "否则建议使用\n```\nencoding=\"utf-8\"\n```\n 。在模式后面加上一个\n```\n'b'\n```\n ，可以用 binary mode 打开文件。",
            "page": None, "section": "7.2 读写文件",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_43"],
        "acceptable_answer_points": ["utf-8"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；模糊提问构造（low_answerable）",
    },
    "zh-029": {
        "query": "教程中提到，用哪个标准库模块可以把结构化数据保存成 JSON 格式？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_45",
            "chunk_text_snippet": "标准库模块 json 可以接受带有层级结构的 Python 数据，并将其转换为字符串表示形式",
            "page": None, "section": "7.2.2 使用 json 保存结构化数据",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_45"],
        "acceptable_answer_points": ["json 模块"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；模糊提问构造（low_answerable）",
    },
    "zh-030": {
        "query": "教程里把错误分成了哪两大类？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_46",
            "chunk_text_snippet": "错误可（至少）被分为两种：语法错误 和 异常",
            "page": None, "section": "8. 错误和异常",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_46"],
        "acceptable_answer_points": ["语法错误", "异常"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-031": {
        "query": "try 语句的 except 子句里，类匹配的规则是什么？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_47",
            "chunk_text_snippet": "一个\n```\nexcept\n```\n 子句中的类匹配的异常将是该类本身的实例或其所派生的类的实例（但反过来则不可以 --- 列出派生类的 except 子句 不会匹配其基类的实例）。",
            "page": None, "section": "8.3 异常的处理",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_47"],
        "acceptable_answer_points": ["匹配该类本身实例或其派生类实例", "反过来（列出派生类去匹配基类）不可以"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-032": {
        "query": "教程中 ExceptionGroup 是用来做什么的？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_52",
            "chunk_text_snippet": "内置的 ExceptionGroup 打包了一个异常实例的列表，这样它们就可以一起被引发",
            "page": None, "section": "8.9 引发和处理多个不相关的异常",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_52"],
        "acceptable_answer_points": ["打包异常实例列表", "让多个异常一起被引发"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-033": {
        "query": "教程里 finally 子句的作用是什么？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_50",
            "chunk_text_snippet": "try 语句还有一个可选子句，用于定义在所有情况下都必须要执行的清理操作",
            "page": None, "section": "8.7 定义清理操作",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_50"],
        "acceptable_answer_points": ["定义所有情况下都必须执行的清理操作"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-034": {
        "query": "类定义进入时，会创建一个什么对象作为局部作用域？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_59",
            "chunk_text_snippet": "当进入类定义时，将创建一个新的命名空间，并将其用作局部作用域",
            "page": None, "section": "9.3.1 类定义语法",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_59"],
        "acceptable_answer_points": ["新的命名空间"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-035": {
        "query": "教程里那个存放斐波那契数列函数的文件叫什么名字？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_30",
            "chunk_text_snippet": "例如，用文本编辑器在当前目录下创建 fibo.py 文件，输入以下内容",
            "page": None, "section": "6. 模块",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_30"],
        "acceptable_answer_points": ["fibo.py"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；模糊提问构造（low_answerable）",
    },
    "zh-036": {
        "query": "模块的编译版本缓存在哪个目录里？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_32",
            "chunk_text_snippet": "Python 把模块的编译版本缓存在 __pycache__ 目录中",
            "page": None, "section": "6.1.3 已编译的 Python 文件",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_32"],
        "acceptable_answer_points": ["__pycache__ 目录"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；模糊提问构造（low_answerable）",
    },
    "zh-037": {
        "query": "dir() 内置函数返回的结果是什么形式的？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_33",
            "chunk_text_snippet": "内置函数 dir() 用于查找模块定义的名称。返回结果是经过排序的字符串列表",
            "page": None, "section": "6.3 dir() 函数",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_33"],
        "acceptable_answer_points": ["经过排序的字符串列表"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── metadata zh（python 相关）──────────────────────────────────
    "zh-038": {
        "query": "这份 Python 教程文档是面向什么样的读者设计的？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_0",
            "chunk_text_snippet": "本教程被设计为针对新入门 Python 语言的 程序员，而 不是 新入门编程的 初学者",
            "page": None, "section": "引言",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_0"],
        "acceptable_answer_points": ["新入门 Python 语言的程序员", "不是新入门编程的初学者"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-039": {
        "query": "教程中提到，Python 解释器和标准库在哪里免费提供？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_0",
            "chunk_text_snippet": "Python 解释器及丰富的标准库针对所有主流系统平台以源代码或二进制形式在 Python 网站 https://www.python.org/ 上免费提供",
            "page": None, "section": "引言",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_0"],
        "acceptable_answer_points": ["Python 官网 https://www.python.org/"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-040": {
        "query": "教程一共包含哪些章节？（说出至少三个章节名）",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_1",
            "chunk_text_snippet": "- 6. 模块\n- 6.1. 模块详解\n- 6.1.1. 以脚本方式执行模块\n\n- 6.1.2. 模块搜索路径",
            "page": None, "section": "目录",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_1"],
        "acceptable_answer_points": ["模块", "输入与输出", "错误和异常"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-041": {
        "query": "教程中提到，包是通过什么方式来构造 Python 模块命名空间的？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_36",
            "chunk_text_snippet": "包是通过使用“带点号模块名”来构造 Python 模块命名空间的一种方式",
            "page": None, "section": "6.4 包",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_36"],
        "acceptable_answer_points": ["带点号模块名（如 A.B）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-042": {
        "query": "教程里演示字符串切片时，用的是什么单词作为示例？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_5",
            "chunk_text_snippet": "还可以这样理解切片，索引指向的是字符 之间 ，第一个字符的左侧标为 0，最后一个字符的右侧标为 n ，n 是字符串长度。",
            "page": None, "section": "3.1.2 文本",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_5"],
        "acceptable_answer_points": ["word（示例为 'Python' 的切片）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-043": {
        "query": "教程中关于作用域，最内层作用域包含什么名称？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_58",
            "chunk_text_snippet": "最内层作用域，包含局部名称，并首先在其中进行搜索",
            "page": None, "section": "9.2 Python 作用域和命名空间",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_58"],
        "acceptable_answer_points": ["局部名称"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-044": {
        "query": "教程中 5.4 节讲的是哪种数据类型？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_26",
            "chunk_text_snippet": "## 5.4. 集合¶ Python 还包括一个表示 集合 的数据类型",
            "page": None, "section": "5.4 集合",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_26"],
        "acceptable_answer_points": ["集合（set）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── mixed_intent zh（python 相关）──────────────────────────────
    "zh-055": {
        "query": "教程里 print(f'Results of the {year} {event}') 这种写法叫什么名字？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_39",
            "chunk_text_snippet": "使用 格式化字符串字面值 ，要在字符串开头的引号/三引号前添加 f 或 F",
            "page": None, "section": "7.1.1 格式化字符串字面值",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_39"],
        "acceptable_answer_points": ["格式化字符串字面值（f-string）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-056": {
        "query": "str() 和 repr() 函数有什么区别？请根据教程举例说明。",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_40",
            "chunk_text_snippet": ">>> s = 'Hello, world.'\n>>> str(s)\n'Hello, world.'\n>>> repr(s)\n\"'Hello, world.'\"",
            "page": None, "section": "7.1.1 格式化字符串字面值",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_40"],
        "acceptable_answer_points": ["str() 返回可读形式", "repr() 返回带引号/反斜杠的表示形式"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-057": {
        "query": "教程中 4.1 节的 while 循环例子用到了多重赋值，请说明等号右边表达式的求值时机。",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_7",
            "chunk_text_snippet": "等号右边的所有表达式的值，都是在这一语句对任何变量赋新值之前求出来的——求值顺序为从左到右",
            "page": None, "section": "4.1 while 循环（斐波那契例子）",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_7"],
        "acceptable_answer_points": ["先求值右边所有表达式", "赋值前完成求值，顺序从左到右"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-058": {
        "query": "教程里说列表是 mutable 的，而字符串是 immutable 的，这具体意味着什么？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_6",
            "chunk_text_snippet": "与 immutable 字符串不同, 列表是 mutable 类型，其内容可以改变",
            "page": None, "section": "3.1.2 文本",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_6"],
        "acceptable_answer_points": ["列表内容可以改变（如 cubes[3] = 64）", "字符串内容不可变"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-059": {
        "query": "教程第 6 章之前，第 5 章讲完数据结构后，接下来介绍的是哪个主题？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_30",
            "chunk_text_snippet": "# 6. 模块¶\n 退出 Python 解释器后，再次进入时，之前在 Python 解释器中定义的函数和变量就丢失了。",
            "page": None, "section": "6. 模块",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_30"],
        "acceptable_answer_points": ["模块（第 6 章）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
}
