"""Corpus v2 annotation content — part D (cross_document, no_answer, mixed_intent, cross chains)."""

CASES_D = {
    # ── chain multi-025 (sqlite → postgresql cross, 3 turns, R3 refusal) ──
    "multi-027": {
        "query": "SQLite 文档中，事务是如何开始的？",
        "relevant_source_ids": ["sqlite-lang.md"],
        "relevant_chunks": [{
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_1",
            "chunk_text_snippet": "sql-stmt:\n      EXPLAIN    QUERY    PLAN          alter-table-stmt       analyze-stmt       attach-stmt       begin-stmt       commit-stmt",
            "page": None, "section": "SQLite SQL 语言概述（语法清单）",
        }],
        "relevant_chunk_ids": ["8b191b241b93_chunk_1"],
        "acceptable_answer_points": ["BEGIN TRANSACTION（begin-stmt）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-028": {
        "query": "那 PostgreSQL 教程里，事务块用哪些命令控制？",
        "relevant_source_ids": ["postgresql-tutorial.md"],
        "relevant_chunks": [{
            "source_id": "postgresql-tutorial.md",
            "chunk_id": "761b22915b5e_chunk_13",
            "chunk_text_snippet": "Some client libraries issue BEGIN and COMMIT commands automatically, so that you might get the effect of transaction blocks without asking",
            "page": None, "section": "3.4 Transactions",
        }],
        "relevant_chunk_ids": ["761b22915b5e_chunk_13"],
        "acceptable_answer_points": ["BEGIN / COMMIT（以及 ROLLBACK）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-029": {
        "query": "那这两篇文档对事务隔离级别的定义一样吗？",
        "relevant_source_ids": [],
        "relevant_chunks": [],
        "relevant_chunk_ids": [],
        "acceptable_answer_points": [],
        "should_refuse": True, "relevance_level": "none",
        "is_refusal_turn": True,
        "review_notes": "LLM_ASSISTED；拒答轮：SQLite 语法页与 PG 教程均未定义隔离级别，两文档均无证据",
    },
    # ── chain multi-028 (python-tutorial-zh → en, 2 turns) ──────────
    "multi-030": {
        "query": "中文教程 3.1.1 节讲的是什么内容？",
        "relevant_source_ids": ["python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_3",
            "chunk_text_snippet": "交互模式下，上次输出的表达式会赋给变量\n```\n_\n```\n。把 Python 当作计算器时，用该变量实现下一步计算更简单，例如：",
            "page": None, "section": "3.1.1 数字",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_3"],
        "acceptable_answer_points": ["数字（把 Python 当作计算器）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-031": {
        "query": "英文版教程里对应的 3.1.1 小节标题是什么？",
        "relevant_source_ids": ["python-tutorial-en.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-en.md",
            "chunk_id": "e564a122a7a2_chunk_7",
            "chunk_text_snippet": "### 3.1.1. Numbers¶\n The interpreter acts as a simple calculator",
            "page": None, "section": "3.1.1 Numbers",
        }],
        "relevant_chunk_ids": ["e564a122a7a2_chunk_7"],
        "acceptable_answer_points": ["Numbers"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── cross_document zh ───────────────────────────────────────────
    "zh-045": {
        "query": "教程正文和 3.13 新特性文档里都出现了 GIL 这个词，它们各自在什么语境下提到它？",
        "relevant_source_ids": ["python-whatsnew313-zh.md", "python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-whatsnew313-zh.md",
            "chunk_id": "81544765752f_chunk_3",
            "chunk_text_snippet": "现在 CPython 具有对运行于禁用 global interpreter lock (GIL) 的自由线程模式的实验性支持",
            "page": None, "section": "自由线程的 CPython",
        }, {
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_0",
            "chunk_text_snippet": "Python 是一门易于学习、功能强大的编程语言",
            "page": None, "section": "引言",
        }],
        "relevant_chunk_ids": ["81544765752f_chunk_3", "32c427fb50e2_chunk_0"],
        "acceptable_answer_points": ["3.13 新特性文档在自由线程模式语境下提到 GIL", "教程正文中未讨论 GIL（仅代码示例可能含英文术语）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；low_answerable 构造：GIL 只在新特性文档有实质讨论",
    },
    "zh-046": {
        "query": "SQLite 和 PostgreSQL 的文档里都讲了数据库创建，两边的说法有什么不同？",
        "relevant_source_ids": ["sqlite-lang.md", "postgresql-tutorial.md"],
        "relevant_chunks": [{
            "source_id": "postgresql-tutorial.md",
            "chunk_id": "761b22915b5e_chunk_6",
            "chunk_text_snippet": "Database names must have an alphabetic first character and are limited to 63 bytes in length",
            "page": None, "section": "1. Getting Started",
        }, {
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_9",
            "chunk_text_snippet": "Tables may be created in the main database, the temp database, or in any attached database.",
            "page": None, "section": "CREATE TABLE",
        }],
        "relevant_chunk_ids": ["761b22915b5e_chunk_6", "8b191b241b93_chunk_9"],
        "acceptable_answer_points": ["PG 用 createdb 且数据库名有限制（字母开头、63 字节）", "SQLite 文档侧重表可建在 main/temp/attached 数据库"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；low_answerable 构造（间接对比）",
    },
    "zh-047": {
        "query": "中文教程和英文教程对第 3 章章节编号的用法一致吗？",
        "relevant_source_ids": ["python-tutorial-zh.md", "python-tutorial-en.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_2",
            "chunk_text_snippet": "# 3. Python 速览¶ 下面的例子以是否显示提示符 (>>> 与 ...) 区分输入与输出",
            "page": None, "section": "3. Python 速览",
        }, {
            "source_id": "python-tutorial-en.md",
            "chunk_id": "e564a122a7a2_chunk_5",
            "chunk_text_snippet": "3. An Informal Introduction to Python",
            "page": None, "section": "3. An Informal Introduction to Python",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_2", "e564a122a7a2_chunk_5"],
        "acceptable_answer_points": ["一致：两版第 3 章标题不同但编号相同（中文为「Python 速览」，英文为「An Informal Introduction to Python」）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；near_band 构造（需跨文档对照章节号）",
    },
    "zh-048": {
        "query": "术语表说 mutable 是什么？而 datetime 文档中哪个类是 immutable 的？",
        "relevant_source_ids": ["python-glossary-zh.md", "python-datetime-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_13",
            "chunk_text_snippet": "mutable -- 可变对象¶ 一种带有在程序运行期间允许修改的状态的 object",
            "page": None, "section": "mutable 可变对象",
        }, {
            "source_id": "python-datetime-zh.md",
            "chunk_id": "2e79918eccf4_chunk_10",
            "chunk_text_snippet": ">>> # 日期对象是不可变的；所有操作都将产生一个新对象\n>>> d.replace(year=2005)\ndatetime.date(2005, 3, 11)",
            "page": None, "section": "datetime 对象",
        }],
        "relevant_chunk_ids": ["c9fd20815ea8_chunk_13", "2e79918eccf4_chunk_10"],
        "acceptable_answer_points": ["mutable 指运行期间允许修改状态的对象", "datetime 对象（date/datetime）不可变"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-049": {
        "query": "Vue 和 React 的文档各自怎么称呼\"组件在模板/界面中的复用单元\"？",
        "relevant_source_ids": ["vue-guide-zh.md", "react-learn-zh.md"],
        "relevant_chunks": [{
            "source_id": "vue-guide-zh.md",
            "chunk_id": "5927c70d0f8e_chunk_19",
            "chunk_text_snippet": "# 组件基础\n\n# Components Basics {#components-basics}",
            "page": None, "section": "组件基础",
        }, {
            "source_id": "react-learn-zh.md",
            "chunk_id": "993955159403_chunk_0",
            "chunk_text_snippet": "React 是一个用于构建用户界面（UI）的 JavaScript 库，用户界面由按钮、文本和图像等小单元内容构建而成。React 帮助你把它们组合成可重用、可嵌套的 *组件*。",
            "page": None, "section": "描述界面",
        }],
        "relevant_chunk_ids": ["5927c70d0f8e_chunk_19", "993955159403_chunk_0"],
        "acceptable_answer_points": ["Vue 文档称「组件」（Components Basics）", "React 文档称「组件」（可复用的小单元）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "zh-050": {
        "query": "3.13 新特性文档中提到 datetime 模块有哪些变化？",
        "relevant_source_ids": ["python-whatsnew313-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-whatsnew313-zh.md",
            "chunk_id": "81544765752f_chunk_44",
            "chunk_text_snippet": "需要 SQLite 3.15.2 或更新的版本才能构建\n```\nsqlite3\n```\n 扩展模块。",
            "page": None, "section": "构建依赖",
        }],
        "relevant_chunk_ids": ["81544765752f_chunk_44"],
        "acceptable_answer_points": ["3.13 新特性文档未列出 datetime 模块的变更"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；跨文档否定查询：新特性文档无 datetime 条目（以其他模块条目佐证文档结构）",
    },
    "zh-051": {
        "query": "教程里提到 REPL 相关的交互式使用，术语表里 REPL 的全称是什么？",
        "relevant_source_ids": ["python-glossary-zh.md", "python-tutorial-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_17",
            "chunk_text_snippet": "REPL¶\n“读取 - 求值 - 打印循环”read-eval-print loop 的缩写，interactive 解释器 shell 的另一个名字。",
            "page": None, "section": "REPL",
        }, {
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_2",
            "chunk_text_snippet": "下面的例子以是否显示提示符 (>>> 与 ...) 区分输入与输出",
            "page": None, "section": "3. Python 速览",
        }],
        "relevant_chunk_ids": ["c9fd20815ea8_chunk_17", "32c427fb50e2_chunk_2"],
        "acceptable_answer_points": ["read-eval-print loop（读取-求值-打印循环）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；low_answerable（跨文档定位）",
    },
    "zh-052": {
        "query": "SQLite 与 PostgreSQL 文档中，对\"事务\"一词的出现位置有什么差异？",
        "relevant_source_ids": ["sqlite-lang.md", "postgresql-tutorial.md"],
        "relevant_chunks": [{
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_1",
            "chunk_text_snippet": "sql-stmt:\n      EXPLAIN    QUERY    PLAN          alter-table-stmt       analyze-stmt       attach-stmt       begin-stmt       commit-stmt",
            "page": None, "section": "语法清单",
        }, {
            "source_id": "postgresql-tutorial.md",
            "chunk_id": "761b22915b5e_chunk_11",
            "chunk_text_snippet": "Simplifying outrageously, the SQL commands for this might look like:  UPDATE accounts SET balance = balance - 100.00 WHERE name = 'Alice';",
            "page": None, "section": "3.4 Transactions",
        }],
        "relevant_chunk_ids": ["8b191b241b93_chunk_1", "761b22915b5e_chunk_11"],
        "acceptable_answer_points": ["SQLite 语法页仅以 begin-stmt 出现在语法清单", "PG 教程第 3 章有专门 Transactions 小节"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；low_answerable（模糊对比）",
    },
    "zh-053": {
        "query": "Python 教程讲文件读写用的 open()，Node.js 文档里对应的函数族叫什么？",
        "relevant_source_ids": ["python-tutorial-zh.md", "nodejs-fs.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_43",
            "chunk_text_snippet": "```\nopen()\n```\n 返回一个 file object ，最常使用的是两个位置参数和一个关键字参数：\n```\nopen(filename, mode, encoding=None)\n```",
            "page": None, "section": "7.2 读写文件",
        }, {
            "source_id": "nodejs-fs.md",
            "chunk_id": "b9c22720dc84_chunk_18",
            "chunk_text_snippet": "import { open } from 'node:fs/promises';\n\nconst fd = await open('/dev/input/event0');",
            "page": None, "section": "fsPromises / FileHandle",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_43", "b9c22720dc84_chunk_18"],
        "acceptable_answer_points": ["Python 教程用 open() 返回 file object", "Node.js 文档用 fs/promises 的 open() 返回 FileHandle"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；near_band（跨文档 API 对照）",
    },
    "zh-054": {
        "query": "术语表中 free-threaded build 条目与 3.13 新特性中的自由线程章节，对 --disable-gil 的描述是否一致？",
        "relevant_source_ids": ["python-glossary-zh.md", "python-whatsnew313-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_7",
            "chunk_text_snippet": "free-threaded build -- 自由线程构建版¶ 支持 free threading 的 CPython 构建版，在编译之前使用了 --disable-gil 选项进行配置",
            "page": None, "section": "free-threaded build",
        }, {
            "source_id": "python-whatsnew313-zh.md",
            "chunk_id": "81544765752f_chunk_3",
            "chunk_text_snippet": "现在 CPython 具有对运行于禁用 global interpreter lock (GIL) 的自由线程模式的实验性支持",
            "page": None, "section": "自由线程的 CPython",
        }],
        "relevant_chunk_ids": ["c9fd20815ea8_chunk_7", "81544765752f_chunk_3"],
        "acceptable_answer_points": ["一致：都以 --disable-gil/禁用 GIL 描述自由线程构建"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── cross_document en ───────────────────────────────────────────
    "en-040": {
        "query": "Compare how the SQLite syntax page and the PostgreSQL tutorial describe transactions.",
        "relevant_source_ids": ["sqlite-lang.md", "postgresql-tutorial.md"],
        "relevant_chunks": [{
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_1",
            "chunk_text_snippet": "sql-stmt:\n      EXPLAIN    QUERY    PLAN          alter-table-stmt       analyze-stmt       attach-stmt       begin-stmt       commit-stmt",
            "page": None, "section": "语法清单",
        }, {
            "source_id": "postgresql-tutorial.md",
            "chunk_id": "761b22915b5e_chunk_11",
            "chunk_text_snippet": "Simplifying outrageously, the SQL commands for this might look like:  UPDATE accounts SET balance = balance - 100.00 WHERE name = 'Alice';",
            "page": None, "section": "3.4 Transactions",
        }],
        "relevant_chunk_ids": ["8b191b241b93_chunk_1", "761b22915b5e_chunk_11"],
        "acceptable_answer_points": ["SQLite lists begin-stmt in the syntax diagram", "PostgreSQL tutorial has a dedicated Transactions section (BEGIN/COMMIT/ROLLBACK)"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-041": {
        "query": "The Python tutorial says simple assignment never copies data — how does that compare with Rust ownership rules?",
        "relevant_source_ids": ["python-tutorial-en.md", "rust-book-core.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-en.md",
            "chunk_id": "e564a122a7a2_chunk_14",
            "chunk_text_snippet": "id(rgb) == id(rgba) # they reference the same object True",
            "page": None, "section": "3.1.3 Lists",
        }, {
            "source_id": "rust-book-core.md",
            "chunk_id": "4f9001ca8c15_chunk_37",
            "chunk_text_snippet": "### Ownership Rules\n\nFirst, let’s take a look at the ownership rules. Keep these rules in mind as we\nwork through the examples that illustrate them:",
            "page": None, "section": "4.1 What Is Ownership",
        }],
        "relevant_chunk_ids": ["e564a122a7a2_chunk_14", "4f9001ca8c15_chunk_37"],
        "acceptable_answer_points": ["Python: assignment references the same object", "Rust: ownership rules govern memory (each value has one owner)"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-042": {
        "query": "RFC 3986 defines URI syntax — does the Node.js fs doc support file URL paths?",
        "relevant_source_ids": ["rfc3986.txt", "nodejs-fs.md"],
        "relevant_chunks": [{
            "source_id": "rfc3986.txt",
            "chunk_id": "86ef1bf559c5_chunk_0",
            "chunk_text_snippet": "Abstract\n\n   A Uniform Resource Identifier (URI) is a compact sequence of\n   characters that identifies an abstract or physical resource.",
            "page": None, "section": "1. Introduction",
        }, {
            "source_id": "nodejs-fs.md",
            "chunk_id": "b9c22720dc84_chunk_13",
            "chunk_text_snippet": "- File URL paths\n- Platform-specific considerations",
            "page": None, "section": "Path options（File URL paths）",
        }],
        "relevant_chunk_ids": ["86ef1bf559c5_chunk_0", "b9c22720dc84_chunk_13"],
        "acceptable_answer_points": ["RFC 3986 defines generic URI syntax", "Node.js fs accepts file URL paths"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-043": {
        "query": "Which of the two database documents mentions type restrictions on columns?",
        "relevant_source_ids": ["sqlite-lang.md", "postgresql-tutorial.md"],
        "relevant_chunks": [{
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_13",
            "chunk_text_snippet": "Unlike most SQL databases, SQLite does not restrict the type of data that may be inserted into a column based on the columns declared type.",
            "page": None, "section": "3.1 Column Data Types",
        }],
        "relevant_chunk_ids": ["8b191b241b93_chunk_13"],
        "acceptable_answer_points": ["SQLite 文档明确说明不限制列数据类型", "PG 教程（start/advanced）未讨论列类型限制"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；low_answerable（否定对比）",
    },
    "en-044": {
        "query": "Where does each document describe how data is passed between components — Rust ownership vs Node.js fs buffers?",
        "relevant_source_ids": ["rust-book-core.md", "nodejs-fs.md"],
        "relevant_chunks": [{
            "source_id": "rust-book-core.md",
            "chunk_id": "4f9001ca8c15_chunk_37",
            "chunk_text_snippet": "### Ownership Rules\n\nFirst, let’s take a look at the ownership rules. Keep these rules in mind as we\nwork through the examples that illustrate them:",
            "page": None, "section": "4.1 What Is Ownership",
        }, {
            "source_id": "nodejs-fs.md",
            "chunk_id": "b9c22720dc84_chunk_22",
            "chunk_text_snippet": "- ``` buffer ``` <Buffer> | <TypedArray> | <DataView> A reference to the passed in ``` buffer ``` argument",
            "page": None, "section": "filehandle.read",
        }],
        "relevant_chunk_ids": ["4f9001ca8c15_chunk_37", "b9c22720dc84_chunk_22"],
        "acceptable_answer_points": ["Rust: ownership rules govern value passing", "Node.js: buffers passed by reference"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；low_answerable",
    },
    "en-045": {
        "query": "Both the Python tutorial and RFC 3986 discuss strings — what encoding-related mechanism does each mention?",
        "relevant_source_ids": ["python-tutorial-en.md", "rfc3986.txt"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-en.md",
            "chunk_id": "e564a122a7a2_chunk_8",
            "chunk_text_snippet": "To quote a quote, we need to “escape” it, by preceding it with\n```\n\\\n```\n.",
            "page": None, "section": "3.1.2 Strings",
        }, {
            "source_id": "rfc3986.txt",
            "chunk_id": "86ef1bf559c5_chunk_19",
            "chunk_text_snippet": "2.1. Percent-Encoding A percent-encoding mechanism is used to represent a data octet in a component",
            "page": None, "section": "2.1 Percent-Encoding",
        }],
        "relevant_chunk_ids": ["e564a122a7a2_chunk_8", "86ef1bf559c5_chunk_19"],
        "acceptable_answer_points": ["Python tutorial: backslash escaping for quotes", "RFC 3986: percent-encoding for data octets"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；near_band",
    },
    "en-046": {
        "query": "How do the Python tutorial and the Node.js fs docs each show writing data to a file?",
        "relevant_source_ids": ["python-tutorial-en.md", "nodejs-fs.md"],
        "relevant_chunks": [],
        "relevant_chunk_ids": [],
        "acceptable_answer_points": ["Python tutorial: f.write(string)（教程 7.2.1 文件对象方法）", "Node.js: filehandle.write / fsPromises.writeFile"],
        "should_refuse": False, "relevance_level": "source",
        "review_notes": "LLM_ASSISTED；source-only：答案点散布于两文档多处示例，难以定位单一 chunk",
    },
    "en-047": {
        "query": "Which document covers JOIN operations in SQL: the SQLite syntax page or the PostgreSQL tutorial?",
        "relevant_source_ids": ["sqlite-lang.md", "postgresql-tutorial.md"],
        "relevant_chunks": [{
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_40",
            "chunk_text_snippet": "## 2.2. Special handling of CROSS JOIN.\n There is no difference between the \"INNER JOIN\", \"JOIN\" and \",\" join operators.",
            "page": None, "section": "SELECT（JOIN）",
        }],
        "relevant_chunk_ids": ["8b191b241b93_chunk_40"],
        "acceptable_answer_points": ["SQLite SELECT 页有 JOIN 专门小节（INNER/CROSS/LEFT 等）", "PG 教程收录章节中无 JOIN 专门讲解（第 2 章未收录）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-048": {
        "query": "The tutorial mentions window functions in PostgreSQL — what SQLite statement uses the OVER clause per its syntax page?",
        "relevant_source_ids": ["postgresql-tutorial.md", "sqlite-lang.md"],
        "relevant_chunks": [{
            "source_id": "postgresql-tutorial.md",
            "chunk_id": "761b22915b5e_chunk_16",
            "chunk_text_snippet": "rank needs no explicit parameter, because its behavior is entirely determined by the OVER clause.",
            "page": None, "section": "3.5 Window Functions",
        }, {
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_8",
            "chunk_text_snippet": "over-clause: show OVER win",
            "page": None, "section": "SELECT 语法",
        }],
        "relevant_chunk_ids": ["761b22915b5e_chunk_16", "8b191b241b93_chunk_8"],
        "acceptable_answer_points": ["PG 教程：window functions 由 OVER 子句决定", "SQLite：语法图包含 over-clause（OVER win）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-049": {
        "query": "The Rust book introduces the String type — which SQLite type name maps to a string?",
        "relevant_source_ids": ["rust-book-core.md", "sqlite-lang.md"],
        "relevant_chunks": [{
            "source_id": "rust-book-core.md",
            "chunk_id": "4f9001ca8c15_chunk_38",
            "chunk_text_snippet": "### The `String` Type\n\nTo illustrate the rules of ownership, we need a data type that is more complex\nthan those we covered in the [“Data Types”][data-types]<!-- ignore --> section\nof Chapter 3.",
            "page": None, "section": "4.1 What Is Ownership",
        }, {
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_12",
            "chunk_text_snippet": "Expression Affinity Column Declared Type\n | TEXT  | \"TEXT\"\n | NUMERIC  | \"NUM\"\n | INTEGER  | \"INT\"",
            "page": None, "section": "CREATE TABLE（亲和性）",
        }],
        "relevant_chunk_ids": ["4f9001ca8c15_chunk_38", "8b191b241b93_chunk_12"],
        "acceptable_answer_points": ["Rust: String type owns heap memory", "SQLite: TEXT affinity for string columns"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；low_answerable",
    },
    "en-050": {
        "query": "Node.js fs supports file URL paths — which RFC defines the syntax of those URLs?",
        "relevant_source_ids": ["nodejs-fs.md", "rfc3986.txt"],
        "relevant_chunks": [{
            "source_id": "nodejs-fs.md",
            "chunk_id": "b9c22720dc84_chunk_13",
            "chunk_text_snippet": "- File URL paths\n- Platform-specific considerations",
            "page": None, "section": "Path options",
        }, {
            "source_id": "rfc3986.txt",
            "chunk_id": "86ef1bf559c5_chunk_0",
            "chunk_text_snippet": "Request for Comments: 3986",
            "page": None, "section": "Header",
        }],
        "relevant_chunk_ids": ["b9c22720dc84_chunk_13", "86ef1bf559c5_chunk_0"],
        "acceptable_answer_points": ["RFC 3986 defines URI generic syntax (file URLs follow it)"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；low_answerable",
    },
    "en-051": {
        "query": "Python lists are sequences; how does SQLite model rows of a table as data?",
        "relevant_source_ids": ["python-tutorial-en.md", "sqlite-lang.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-en.md",
            "chunk_id": "e564a122a7a2_chunk_14",
            "chunk_text_snippet": "rgb = [\"Red\", \"Green\", \"Blue\"]",
            "page": None, "section": "3.1.3 Lists",
        }, {
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_24",
            "chunk_text_snippet": "The result of a SELECT is zero or more rows of data where each row has a fixed number of columns.",
            "page": None, "section": "SELECT",
        }],
        "relevant_chunk_ids": ["e564a122a7a2_chunk_14", "8b191b241b93_chunk_24"],
        "acceptable_answer_points": ["Python: lists as mutable sequences", "SQLite: SELECT returns rows with a fixed number of columns"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；near_band",
    },
    "en-052": {
        "query": "Both PostgreSQL and Rust documents discuss guarantees — what does each guarantee about data consistency?",
        "relevant_source_ids": ["postgresql-tutorial.md", "rust-book-core.md"],
        "relevant_chunks": [{
            "source_id": "postgresql-tutorial.md",
            "chunk_id": "761b22915b5e_chunk_12",
            "chunk_text_snippet": "A transactional database guarantees that all the updates made by a transaction are logged in permanent storage",
            "page": None, "section": "3.4 Transactions",
        }, {
            "source_id": "rust-book-core.md",
            "chunk_id": "4f9001ca8c15_chunk_37",
            "chunk_text_snippet": "### Ownership Rules\n\nFirst, let’s take a look at the ownership rules. Keep these rules in mind as we\nwork through the examples that illustrate them:",
            "page": None, "section": "4.1 What Is Ownership",
        }],
        "relevant_chunk_ids": ["761b22915b5e_chunk_12", "4f9001ca8c15_chunk_37"],
        "acceptable_answer_points": ["PostgreSQL: transaction durability (logged to disk)", "Rust: ownership rules guarantee memory safety"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "en-053": {
        "query": "Both the Art of War and the SQLite docs praise flexibility — quote the corresponding statements.",
        "relevant_source_ids": ["art-of-war.txt", "sqlite-lang.md"],
        "relevant_chunks": [{
            "source_id": "art-of-war.txt",
            "chunk_id": "293d777c429b_chunk_94",
            "chunk_text_snippet": "Military tactics are like unto water; for water in its natural\ncourse runs away from high places and hastens downwards.",
            "page": None, "section": "Chapter VI 兵势（示例行）",
        }, {
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_13",
            "chunk_text_snippet": "Unlike most SQL databases, SQLite does not restrict the type of data that may be inserted into a column based on the columns declared type.",
            "page": None, "section": "3.1 Column Data Types",
        }],
        "relevant_chunk_ids": ["293d777c429b_chunk_94", "8b191b241b93_chunk_13"],
        "acceptable_answer_points": ["Art of War: 兵形象水（tactics are like water）", "SQLite: 不限制列数据类型"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；跨文档主题整合（两文档都强调灵活性）",
    },
    # ── cross_document mixed ────────────────────────────────────────
    "mixed-026": {
        "query": "中文教程把第 3 章叫做 Python 速览，英文教程叫 An Informal Introduction to Python，两版内容对应吗？",
        "relevant_source_ids": ["python-tutorial-zh.md", "python-tutorial-en.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_2",
            "chunk_text_snippet": "# 3. Python 速览¶",
            "page": None, "section": "3. Python 速览",
        }, {
            "source_id": "python-tutorial-en.md",
            "chunk_id": "e564a122a7a2_chunk_5",
            "chunk_text_snippet": "3. An Informal Introduction to Python",
            "page": None, "section": "3. An Informal Introduction to Python",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_2", "e564a122a7a2_chunk_5"],
        "acceptable_answer_points": ["对应：同一章，标题翻译不同", "内容均为非正式介绍（计算器、字符串、列表示例）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "mixed-027": {
        "query": "术语表说 atomic operation 不可再分，SQLite 文档里事务的原子性体现在哪？",
        "relevant_source_ids": ["python-glossary-zh.md", "sqlite-lang.md"],
        "relevant_chunks": [{
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_2",
            "chunk_text_snippet": "atomic operation -- 原子化操作¶ 作为一个单独的、不可再分的步骤执行的操作",
            "page": None, "section": "atomic operation",
        }, {
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_1",
            "chunk_text_snippet": "sql-stmt:\n      EXPLAIN    QUERY    PLAN          alter-table-stmt       analyze-stmt       attach-stmt       begin-stmt       commit-stmt",
            "page": None, "section": "语法清单",
        }],
        "relevant_chunk_ids": ["c9fd20815ea8_chunk_2", "8b191b241b93_chunk_1"],
        "acceptable_answer_points": ["术语表：原子化操作不可再分", "SQLite 语法页仅列出 begin-stmt，未展开事务原子性说明"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；low_answerable（否定对比）",
    },
    "mixed-028": {
        "query": "Vue 的响应式（reactive）和 React 的 state 在概念上有什么共同点？",
        "relevant_source_ids": ["vue-guide-zh.md", "react-learn-zh.md"],
        "relevant_chunks": [{
            "source_id": "vue-guide-zh.md",
            "chunk_id": "5927c70d0f8e_chunk_9",
            "chunk_text_snippet": "In Vue 3, data is made reactive by leveraging JavaScript Proxies",
            "page": None, "section": "响应式基础",
        }, {
            "source_id": "react-learn-zh.md",
            "chunk_id": "993955159403_chunk_7",
            "chunk_text_snippet": "## State: 组件的记忆",
            "page": None, "section": "添加交互",
        }],
        "relevant_chunk_ids": ["5927c70d0f8e_chunk_9", "993955159403_chunk_7"],
        "acceptable_answer_points": ["两者都让数据变化驱动界面更新", "Vue 用 Proxy 实现响应式，React 用 state 记忆组件"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；low_answerable",
    },
    "mixed-029": {
        "query": "术语表里 free-threaded build 与 3.13 新特性的自由线程章节，构建方式说法是否一致？",
        "relevant_source_ids": ["python-glossary-zh.md", "python-whatsnew313-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_7",
            "chunk_text_snippet": "在编译之前使用了 --disable-gil 选项进行配置",
            "page": None, "section": "free-threaded build",
        }, {
            "source_id": "python-whatsnew313-zh.md",
            "chunk_id": "81544765752f_chunk_3",
            "chunk_text_snippet": "对运行于禁用 global interpreter lock (GIL) 的自由线程模式的实验性支持",
            "page": None, "section": "自由线程的 CPython",
        }],
        "relevant_chunk_ids": ["c9fd20815ea8_chunk_7", "81544765752f_chunk_3"],
        "acceptable_answer_points": ["一致：都指 --disable-gil/禁用 GIL 的自由线程构建"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；near_band",
    },
    "mixed-030": {
        "query": "Python 教程里介绍类和组件概念，React 文档中的组件概念和它有什么对应？",
        "relevant_source_ids": ["python-tutorial-zh.md", "react-learn-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-tutorial-zh.md",
            "chunk_id": "32c427fb50e2_chunk_59",
            "chunk_text_snippet": "最简单的类定义形式如下：\n\n```\nclass ClassName:\n    <语句-1>\n    .\n    .\n    .\n    <语句-N>\n```",
            "page": None, "section": "9.3.1 类定义语法",
        }, {
            "source_id": "react-learn-zh.md",
            "chunk_id": "993955159403_chunk_0",
            "chunk_text_snippet": "React 是一个用于构建用户界面（UI）的 JavaScript 库",
            "page": None, "section": "描述界面",
        }],
        "relevant_chunk_ids": ["32c427fb50e2_chunk_59", "993955159403_chunk_0"],
        "acceptable_answer_points": ["Python 类是可复用代码单元", "React 组件是可复用 UI 单元（两者都是复用封装概念）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "mixed-031": {
        "query": "术语表对 mutable 的定义，和 datetime 文档中日期对象的性质一致吗？",
        "relevant_source_ids": ["python-glossary-zh.md", "python-datetime-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_13",
            "chunk_text_snippet": "mutable -- 可变对象¶ 一种带有在程序运行期间允许修改的状态的 object",
            "page": None, "section": "mutable",
        }, {
            "source_id": "python-datetime-zh.md",
            "chunk_id": "2e79918eccf4_chunk_10",
            "chunk_text_snippet": "日期对象是不可变的；所有操作都将产生一个新对象",
            "page": None, "section": "datetime 对象",
        }],
        "relevant_chunk_ids": ["c9fd20815ea8_chunk_13", "2e79918eccf4_chunk_10"],
        "acceptable_answer_points": ["一致：datetime 对象是不可变的，不属于 mutable"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "mixed-032": {
        "query": "SQLite 语法页与 PostgreSQL 教程中，哪个文档有专门的 JOIN 讲解？",
        "relevant_source_ids": ["sqlite-lang.md", "postgresql-tutorial.md"],
        "relevant_chunks": [{
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_40",
            "chunk_text_snippet": "## 2.2. Special handling of CROSS JOIN.\n There is no difference between the \"INNER JOIN\", \"JOIN\" and \",\" join operators.",
            "page": None, "section": "SELECT（JOIN）",
        }],
        "relevant_chunk_ids": ["8b191b241b93_chunk_40"],
        "acceptable_answer_points": ["SQLite SELECT 页有 JOIN 讲解", "PG 教程收录章节无 JOIN 专门内容"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── mixed_intent mixed ──────────────────────────────────────────
    "mixed-033": {
        "query": "术语表里 static type checker 和 stdlib 分别指什么？",
        "relevant_source_ids": ["python-glossary-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_18",
            "chunk_text_snippet": "static type checker -- 静态类型检查器¶ 读取 Python 代码并进行分析，以查找问题例如不正确的类型的外部工具",
            "page": None, "section": "static type checker",
        }, {
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_18",
            "chunk_text_snippet": "stdlib -- 标准库¶\nstandard library 的缩写。",
            "page": None, "section": "stdlib",
        }],
        "relevant_chunk_ids": ["c9fd20815ea8_chunk_18", "c9fd20815ea8_chunk_18"],
        "acceptable_answer_points": ["static type checker 是查找类型问题的外部工具", "stdlib 是标准库（standard library）的缩写"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "mixed-034": {
        "query": "3.13 新特性里 REPL 与 JIT 各有什么改进？",
        "relevant_source_ids": ["python-whatsnew313-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-whatsnew313-zh.md",
            "chunk_id": "81544765752f_chunk_2",
            "chunk_text_snippet": "- 多行编辑并保留历史记录。\n\n- 对 REPL 专属的命令如\n```\nhelp\n```\n,\n```\nexit\n```\n 和\n```\nquit\n```\n 的直接支持",
            "page": None, "section": "REPL 改进",
        }, {
            "source_id": "python-whatsnew313-zh.md",
            "chunk_id": "81544765752f_chunk_4",
            "chunk_text_snippet": "-\n```\nyes\n```\n: 启用 JIT。 要在运行时禁用 JIT，则传入环境变量\n```\nPYTHON_JIT=0\n```\n。",
            "page": None, "section": "JIT 编译器",
        }],
        "relevant_chunk_ids": ["81544765752f_chunk_2", "81544765752f_chunk_4"],
        "acceptable_answer_points": ["REPL：多行编辑、命令历史、help/exit/quit 直接支持", "JIT：可用 PYTHON_JIT 环境变量控制"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "mixed-035": {
        "query": "术语表中，generator iterator 的中文名和 bytecode 的中文名是什么？",
        "relevant_source_ids": ["python-glossary-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_8",
            "chunk_text_snippet": "generator iterator -- 生成器迭代器¶ An object created by a generator function or a generator expression",
            "page": None, "section": "generator iterator",
        }, {
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_3",
            "chunk_text_snippet": "bytecode -- 字节码¶ Python 源代码会被编译为字节码",
            "page": None, "section": "bytecode 字节码",
        }],
        "relevant_chunk_ids": ["c9fd20815ea8_chunk_8", "c9fd20815ea8_chunk_3"],
        "acceptable_answer_points": ["生成器迭代器", "字节码"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── no_answer zh ────────────────────────────────────────────────
    "noanswer-026": {
        "query": "Python 教程中介绍了 pandas 库的 DataFrame 用法吗？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：pandas 主题与教程相近但语料无任何 pandas 内容",
    },
    "noanswer-027": {
        "query": "教程里讲没讲过 Django 框架的部署方式？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：主题相近（Python 生态）但无证据",
    },
    "noanswer-028": {
        "query": "Python 3.13 新特性文档中提到 Go 语言的相关内容了吗？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：跨语言主题，语料无 Go 内容",
    },
    "noanswer-029": {
        "query": "术语表中有没有 Django 的条目？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse",
    },
    "noanswer-030": {
        "query": "教程中对比了 Python 与 C 语言的具体性能数据吗？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；normal：教程提及 C 语言但无性能对比数据",
    },
    "noanswer-031": {
        "query": "教程里说明了 CPython 解释器的 C 源码在哪个仓库路径吗？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；normal：教程未给出源码路径",
    },
    "noanswer-032": {
        "query": "SQLite 语法文档里 PRAGMA journal_mode 的用法说明在哪？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：SQLite 主题相近但收录的语法页无 PRAGMA 内容",
    },
    "noanswer-033": {
        "query": "PostgreSQL 教程中讲流式复制（streaming replication）的配置了吗？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：PG 主题相近但教程（start/advanced）无复制内容",
    },
    "noanswer-034": {
        "query": "Vue 指南文档里有专门的 TypeScript 章节吗？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：收录的 essentials 章节无 TypeScript",
    },
    "noanswer-035": {
        "query": "React 文档中介绍了 Testing（测试）章节吗？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：收录的 learn 章节无测试内容",
    },
    "noanswer-036": {
        "query": "Rust 书中第 7 章讲模块系统的内容是什么？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；normal：语料仅收录第 3–6 章，无第 7 章",
    },
    # ── no_answer en ────────────────────────────────────────────────
    "noanswer-037": {
        "query": "Where does the PostgreSQL tutorial explain CREATE ROLE?",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：教程讲 createdb 用户但无 CREATE ROLE 语法",
    },
    "noanswer-038": {
        "query": "Does RFC 3986 define the about: URI scheme?",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：RFC 3986 不定义具体 scheme",
    },
    "noanswer-039": {
        "query": "Does the Node.js fs doc describe inotify internals of fs.watch on Linux?",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：fs.watch 有 caveats 但无 inotify 内部实现",
    },
    "noanswer-040": {
        "query": "Does the Rust book (chapters included in this corpus) cover traits?",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：收录章节（3–6 章）无 trait",
    },
    "noanswer-041": {
        "query": "Does the Python tutorial explain how to use matplotlib?",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：主题相近（Python 生态）但无 matplotlib",
    },
    "noanswer-042": {
        "query": "Does RFC 3986 cover internationalized URIs (IRI)?",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；normal：IRI 属 RFC 3987，3986 不覆盖",
    },
    "noanswer-043": {
        "query": "What are the birth and death years of Sun Tzu per the Art of War text?",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；normal：文本无作者生卒信息",
    },
    "noanswer-044": {
        "query": "Where does the SQLite syntax doc explain WAL journal mode?",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：收录页无 WAL/PRAGMA 内容",
    },
    "noanswer-045": {
        "query": "Does the PostgreSQL tutorial cover logical replication?",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：教程无逻辑复制内容",
    },
    "noanswer-046": {
        "query": "Does the included Rust book chapters explain how to publish a crate to crates.io?",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：Cargo 发布不在收录章节",
    },
    "noanswer-047": {
        "query": "Does the Node.js fs documentation cover disk quota management?",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse",
    },
    "noanswer-048": {
        "query": "Where does RFC 3986 define the http scheme in detail?",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；normal：http scheme 由其他 RFC 定义",
    },
    "noanswer-049": {
        "query": "Does the Art of War chapter on fire attack provide a gunpowder formula?",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；normal：火攻章讲策略，无配方",
    },
    "noanswer-050": {
        "query": "Does the Python tutorial introduce the unittest framework?",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：教程无 unittest 内容",
    },
    # ── no_answer mixed ─────────────────────────────────────────────
    "noanswer-051": {
        "query": "教程或术语表里提到机器学习框架（如 scikit-learn）的内容了吗？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：主题相近但无证据",
    },
    "noanswer-052": {
        "query": "SQLite 和 PostgreSQL 文档里讲了 JSON 数据类型的功能吗？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：两文档收录内容均无 JSON 数据类型",
    },
    "noanswer-053": {
        "query": "Vue 或 React 文档里有状态管理库（Pinia/Redux）的章节吗？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；low_refuse：收录章节无状态管理库内容",
    },
    "noanswer-054": {
        "query": "语料中有关于 Git 版本控制的内容吗？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；normal：语料无 Git 相关文档",
    },
    "noanswer-055": {
        "query": "语料中有关于云部署（cloud deployment）的内容吗？",
        "relevant_source_ids": [], "relevant_chunks": [], "relevant_chunk_ids": [],
        "acceptable_answer_points": [], "should_refuse": True, "relevance_level": "none",
        "review_notes": "LLM_ASSISTED；normal：语料无云部署内容",
    },
}
