"""Corpus v2 annotation content — part C (chains for sqlite/pg/rust/vue/react + mixed-language cases)."""

CASES_C = {
    # ── chain multi-016 (sqlite-lang, 2 turns) ──────────────────────
    "multi-018": {
        "query": "In the SQLite docs, what does a CHECK constraint do?",
        "relevant_source_ids": ["sqlite-lang.md"],
        "relevant_chunks": [{
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_17",
            "chunk_text_snippet": "## 3.7. CHECK constraints A CHECK constraint may be attached to a column definition or specified as a table constraint",
            "page": None, "section": "3.7 CHECK constraints",
        }],
        "relevant_chunk_ids": ["8b191b241b93_chunk_17"],
        "acceptable_answer_points": ["可附加到列定义或表约束", "用于约束列值（如 x>3）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-019": {
        "query": "Can the database file be modified externally to bypass a CHECK constraint?",
        "relevant_source_ids": ["sqlite-lang.md"],
        "relevant_chunks": [{
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_17",
            "chunk_text_snippet": "## 3.7. CHECK constraints\n A CHECK constraint may be attached to a column definition or specified as a table constraint. In practice it makes no difference.",
            "page": None, "section": "3.7 CHECK constraints",
        }],
        "relevant_chunk_ids": ["8b191b241b93_chunk_17"],
        "acceptable_answer_points": ["可以（示例演示直接写数据库文件绕过约束）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── chain multi-018 (postgresql-tutorial, 2 turns) ─────────────
    "multi-020": {
        "query": "In the PostgreSQL tutorial, what is the first command to create a new database after installation?",
        "relevant_source_ids": ["postgresql-tutorial.md"],
        "relevant_chunks": [{
            "source_id": "postgresql-tutorial.md",
            "chunk_id": "761b22915b5e_chunk_6",
            "chunk_text_snippet": "A convenient choice is to create a database with the same name as your current user name. Many tools assume that database name as the default, so it can save you some typing.",
            "page": None, "section": "1. Getting Started",
        }],
        "relevant_chunk_ids": ["761b22915b5e_chunk_6"],
        "acceptable_answer_points": ["createdb"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-021": {
        "query": "And how do you access that database interactively?",
        "relevant_source_ids": ["postgresql-tutorial.md"],
        "relevant_chunks": [{
            "source_id": "postgresql-tutorial.md",
            "chunk_id": "761b22915b5e_chunk_7",
            "chunk_text_snippet": "In psql, you will be greeted with the following message: psql (&version;)",
            "page": None, "section": "1. Getting Started",
        }],
        "relevant_chunk_ids": ["761b22915b5e_chunk_7"],
        "acceptable_answer_points": ["psql"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── chain multi-020 (rust-book-core, 2 turns) ───────────────────
    "multi-022": {
        "query": "In the Rust book, what happens to a value when its owner goes out of scope?",
        "relevant_source_ids": ["rust-book-core.md"],
        "relevant_chunks": [{
            "source_id": "rust-book-core.md",
            "chunk_id": "4f9001ca8c15_chunk_37",
            "chunk_text_snippet": "- Each value in Rust has an _owner_.\n- There can only be one owner at a time.\n- When the owner goes out of scope, the value will be dropped.",
            "page": None, "section": "4.1 What Is Ownership",
        }],
        "relevant_chunk_ids": ["4f9001ca8c15_chunk_37"],
        "acceptable_answer_points": ["值被丢弃（drop）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-023": {
        "query": "What does the `String::from` function do when called?",
        "relevant_source_ids": ["rust-book-core.md"],
        "relevant_chunks": [{
            "source_id": "rust-book-core.md",
            "chunk_id": "4f9001ca8c15_chunk_40",
            "chunk_text_snippet": "That first part is done by us: When we call `String::from`, its implementation\nrequests the memory it needs. This is pretty much universal in programming\nlanguages.",
            "page": None, "section": "4.1 What Is Ownership",
        }],
        "relevant_chunk_ids": ["4f9001ca8c15_chunk_40"],
        "acceptable_answer_points": ["请求（分配）它需要的内存"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── chain multi-022 (vue-guide-zh, 3 turns) ─────────────────────
    "multi-024": {
        "query": "Vue 文档中，模板里用双大括号写的是什么语法？",
        "relevant_source_ids": ["vue-guide-zh.md"],
        "relevant_chunks": [{
            "source_id": "vue-guide-zh.md",
            "chunk_id": "5927c70d0f8e_chunk_1",
            "chunk_text_snippet": "<p>Using text interpolation: {{ rawHtml }}</p>",
            "page": None, "section": "模板语法 Text Interpolation",
        }],
        "relevant_chunk_ids": ["5927c70d0f8e_chunk_1"],
        "acceptable_answer_points": ["文本插值（text interpolation）{{ }}"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-025": {
        "query": "v-bind 的简写语法是什么？",
        "relevant_source_ids": ["vue-guide-zh.md"],
        "relevant_chunks": [{
            "source_id": "vue-guide-zh.md",
            "chunk_id": "5927c70d0f8e_chunk_2",
            "chunk_text_snippet": "Because `v-bind` is so commonly used, it has a dedicated shorthand syntax: ```vue-html <div :id=\"dynamicId\"></div> ```",
            "page": None, "section": "模板语法 Shorthand",
        }],
        "relevant_chunk_ids": ["5927c70d0f8e_chunk_2"],
        "acceptable_answer_points": ["冒号简写 :id（即 : 前缀）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-026": {
        "query": "响应式基础里说，Vue 3 中数据是通过什么机制变为响应式的？",
        "relevant_source_ids": ["vue-guide-zh.md"],
        "relevant_chunks": [{
            "source_id": "vue-guide-zh.md",
            "chunk_id": "5927c70d0f8e_chunk_9",
            "chunk_text_snippet": "In Vue 3, data is made reactive by leveraging [JavaScript Proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy).",
            "page": None, "section": "响应式基础 Reactive Proxy vs. Original",
        }],
        "relevant_chunk_ids": ["5927c70d0f8e_chunk_9"],
        "acceptable_answer_points": ["JavaScript Proxies（Proxy 代理）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── chain multi-030 (react-learn-zh, 3 turns) ───────────────────
    "multi-032": {
        "query": "React 文档中说，React 是一个用于构建什么的 JavaScript 库？",
        "relevant_source_ids": ["react-learn-zh.md"],
        "relevant_chunks": [{
            "source_id": "react-learn-zh.md",
            "chunk_id": "993955159403_chunk_0",
            "chunk_text_snippet": "React 是一个用于构建用户界面（UI）的 JavaScript 库，用户界面由按钮、文本和图像等小单元内容构建",
            "page": None, "section": "描述界面",
        }],
        "relevant_chunk_ids": ["993955159403_chunk_0"],
        "acceptable_answer_points": ["构建用户界面（UI）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-033": {
        "query": "渲染列表时，每个数组元素需要指定什么？",
        "relevant_source_ids": ["react-learn-zh.md"],
        "relevant_chunks": [{
            "source_id": "react-learn-zh.md",
            "chunk_id": "993955159403_chunk_4",
            "chunk_text_snippet": "对于数组的每个元素项，你需要指定一个 `key`。通常你需要使用数据库中的 ID 作为 `key`",
            "page": None, "section": "描述界面（渲染列表）",
        }],
        "relevant_chunk_ids": ["993955159403_chunk_4"],
        "acceptable_answer_points": ["key（通常用数据库 ID）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "multi-034": {
        "query": "State 被文档称为什么？",
        "relevant_source_ids": ["react-learn-zh.md"],
        "relevant_chunks": [{
            "source_id": "react-learn-zh.md",
            "chunk_id": "993955159403_chunk_7",
            "chunk_text_snippet": "## State: 组件的记忆",
            "page": None, "section": "添加交互（State: 组件的记忆）",
        }],
        "relevant_chunk_ids": ["993955159403_chunk_7"],
        "acceptable_answer_points": ["组件的记忆"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── mixed single_fact ───────────────────────────────────────────
    "mixed-016": {
        "query": "术语表里，argument 和 parameter 的中文译名分别是什么？",
        "relevant_source_ids": ["python-glossary-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_1",
            "chunk_text_snippet": "参数会被赋值给函数体中对应的局部变量。有关赋值规则参见 调用 一节。根据语法，任何表达式都可用来表示一个参数；最终算出的值会被赋给对应的局部变量。\n 另参见 parameter 术语表条目",
            "page": None, "section": "argument 参数",
        }],
        "relevant_chunk_ids": ["c9fd20815ea8_chunk_1"],
        "acceptable_answer_points": ["argument 译为 参数", "parameter 为另一术语表条目（形参）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED；混合中英对照文档",
    },
    "mixed-017": {
        "query": "术语表中 atomic operation 的中文名称是什么？",
        "relevant_source_ids": ["python-glossary-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_2",
            "chunk_text_snippet": "atomic operation -- 原子化操作¶ 作为一个单独的、不可再分的步骤执行的操作",
            "page": None, "section": "atomic operation 原子化操作",
        }],
        "relevant_chunk_ids": ["c9fd20815ea8_chunk_2"],
        "acceptable_answer_points": ["原子化操作"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "mixed-018": {
        "query": "React 文档中，更新 state 中的数组时应该怎样做？",
        "relevant_source_ids": ["react-learn-zh.md"],
        "relevant_chunks": [{
            "source_id": "react-learn-zh.md",
            "chunk_id": "993955159403_chunk_15",
            "chunk_text_snippet": "当你想更新存在状态中的数组时，你需要创建一个新数组（或者复制现有数组），然后用新数组来更新状态",
            "page": None, "section": "更新 state 中的数组",
        }],
        "relevant_chunk_ids": ["993955159403_chunk_15"],
        "acceptable_answer_points": ["创建新数组（或复制现有数组）", "用新数组更新状态"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "mixed-019": {
        "query": "Vue 文档中，ref 与普通变量的一个区别是什么？",
        "relevant_source_ids": ["vue-guide-zh.md"],
        "relevant_chunks": [{
            "source_id": "vue-guide-zh.md",
            "chunk_id": "5927c70d0f8e_chunk_12",
            "chunk_text_snippet": "unlike plain variables, you can pass refs into functions while retaining access to the latest value and the reactivity",
            "page": None, "section": "响应式基础 Refs",
        }],
        "relevant_chunk_ids": ["5927c70d0f8e_chunk_12"],
        "acceptable_answer_points": ["ref 传入函数后仍保留最新值与响应性"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "mixed-020": {
        "query": "SQLite 文档中，CREATE TABLE ... AS SELECT 语句的作用是什么？",
        "relevant_source_ids": ["sqlite-lang.md"],
        "relevant_chunks": [{
            "source_id": "sqlite-lang.md",
            "chunk_id": "8b191b241b93_chunk_11",
            "chunk_text_snippet": "A \"CREATE TABLE ... AS SELECT\" statement creates and populates a database table based on the results of a SELECT",
            "page": None, "section": "2.1 CREATE TABLE ... AS SELECT",
        }],
        "relevant_chunk_ids": ["8b191b241b93_chunk_11"],
        "acceptable_answer_points": ["根据 SELECT 结果创建并填充表"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    # ── mixed metadata ──────────────────────────────────────────────
    "mixed-021": {
        "query": "术语表中 REPL 的全称是什么？",
        "relevant_source_ids": ["python-glossary-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_17",
            "chunk_text_snippet": "REPL¶\n“读取 - 求值 - 打印循环”read-eval-print loop 的缩写，interactive 解释器 shell 的另一个名字。",
            "page": None, "section": "REPL",
        }],
        "relevant_chunk_ids": ["c9fd20815ea8_chunk_17"],
        "acceptable_answer_points": ["read-eval-print loop（读取-求值-打印循环）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "mixed-022": {
        "query": "术语表中，decorator 条目用的是中文还是英文解释？",
        "relevant_source_ids": ["python-glossary-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_5",
            "chunk_text_snippet": "decorator -- 装饰器¶ A function returning another function, usually applied as a function transformation using the @wrapper syntax",
            "page": None, "section": "decorator 装饰器",
        }],
        "relevant_chunk_ids": ["c9fd20815ea8_chunk_5"],
        "acceptable_answer_points": ["英文解释（A function returning another function...）", "中文仅术语名（装饰器）"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "mixed-023": {
        "query": "React 文档中，使用 useReducer 的示例组件叫什么？",
        "relevant_source_ids": ["react-learn-zh.md"],
        "relevant_chunks": [{
            "source_id": "react-learn-zh.md",
            "chunk_id": "993955159403_chunk_23",
            "chunk_text_snippet": "export default function TaskApp() {\n  const [tasks, dispatch] = useReducer(\n    tasksReducer,\n    initialTasks\n  );",
            "page": None, "section": "管理状态（useReducer）",
        }],
        "relevant_chunk_ids": ["993955159403_chunk_23"],
        "acceptable_answer_points": ["TaskApp"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "mixed-024": {
        "query": "Python 术语表中，free-threaded build 对应的中文是什么？",
        "relevant_source_ids": ["python-glossary-zh.md"],
        "relevant_chunks": [{
            "source_id": "python-glossary-zh.md",
            "chunk_id": "c9fd20815ea8_chunk_7",
            "chunk_text_snippet": "free-threaded build -- 自由线程构建版¶ 支持 free threading 的 CPython 构建版",
            "page": None, "section": "free-threaded build 自由线程构建版",
        }],
        "relevant_chunk_ids": ["c9fd20815ea8_chunk_7"],
        "acceptable_answer_points": ["自由线程构建版"],
        "should_refuse": False, "relevance_level": "chunk",
        "review_notes": "LLM_ASSISTED",
    },
    "mixed-025": {
        "query": "Python 3.13 新特性文档的编者是谁？（见文档开头）",
        "relevant_source_ids": ["python-whatsnew313-zh.md"],
        "relevant_chunks": [],
        "relevant_chunk_ids": [],
        "acceptable_answer_points": ["文档开头列出编者（Editors）"],
        "should_refuse": False, "relevance_level": "source",
        "review_notes": "LLM_ASSISTED；source-only：编者姓名位于文档头部元信息，不指向单一内容 chunk",
    },
}
